let counter = 0;

/**
 * Ids for new clips, tracks, notes and log entries. Generated by the client
 * and passed into commands as params so the commands themselves stay
 * deterministic.
 */
export function newId(prefix: string): string {
  counter += 1;
  return `${prefix}-${Date.now().toString(36)}-${counter.toString(36)}`;
}
