//! The C ABI between Ondera and a plugin library.
//!
//! A library exports one symbol, `ondera_plugin_entry`, returning an [`Entry`] whose
//! `plugin(index)` hands out one [`PluginVTable`] per plugin type. Every function in the
//! vtable is generated by [`vtable`] from a [`Plugin`](crate::Plugin) implementation, so
//! plugin authors never write `extern "C"` themselves. The host treats the vtable as an
//! opaque contract: metadata as JSON, one instance pointer per instantiation, and
//! `process` on the audio thread.
//!
//! Hosts other than Ondera can consume the same ABI. Every `repr(C)` layout of ABI 1
//! ([`Entry`], [`PluginVTable`], [`RawContext`], [`NoteEvent`](crate::NoteEvent)) is frozen.
//!
//! ABI 2 does not touch them. A library exports a second symbol, `ondera_plugin_entry_v2`,
//! returning an [`Entry2`] whose [`PluginVTable2`] embeds the ABI 1 table and appends:
//! `process_events` (notes, controllers, pitch bend and pressure, plus parameter changes, all
//! with frame offsets), `save`/`load` of an opaque state blob, and `tail_seconds`.
//! `process_events` returns flags; [`FLAG_LATENCY_CHANGED`] asks the host to read `latency`
//! again. [`export_plugins!`](crate::export_plugins) exports both symbols, so a plugin built
//! today loads in an ABI 1 host, and a host looks for the second symbol and falls back to
//! the first. `PluginVTable2::size` lets later revisions append more without a new symbol.

use crate::{
    Event, Info, Kind, NoteEvent, ParamSpec, Plugin, ProcessContext, TimedParam, ABI_VERSION,
    BASE_ABI_VERSION,
};
use serde::{Deserialize, Serialize};
use std::{ffi::c_void, panic::AssertUnwindSafe};

/// Transport context in a layout that never changes.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct RawContext {
    pub playing: bool,
    pub recording: bool,
    pub cycling: bool,
    pub tempo: f64,
    pub position_beats: f64,
    pub position_seconds: f64,
    pub sample_time: i64,
    pub numerator: u32,
    pub denominator: u32,
    pub cycle_start: f64,
    pub cycle_end: f64,
    pub bar_start_beats: f64,
}
impl From<&ProcessContext> for RawContext {
    fn from(ctx: &ProcessContext) -> Self {
        let (cycle_start, cycle_end) = ctx.cycle.unwrap_or((0.0, 0.0));
        Self {
            playing: ctx.playing,
            recording: ctx.recording,
            cycling: ctx.cycle.is_some(),
            tempo: ctx.tempo,
            position_beats: ctx.position_beats,
            position_seconds: ctx.position_seconds,
            sample_time: ctx.sample_time,
            numerator: ctx.numerator,
            denominator: ctx.denominator,
            cycle_start,
            cycle_end,
            bar_start_beats: ctx.bar_start_beats,
        }
    }
}
impl From<&RawContext> for ProcessContext {
    fn from(raw: &RawContext) -> Self {
        Self {
            playing: raw.playing,
            recording: raw.recording,
            tempo: raw.tempo,
            position_beats: raw.position_beats,
            position_seconds: raw.position_seconds,
            sample_time: raw.sample_time,
            numerator: raw.numerator,
            denominator: raw.denominator,
            cycle: raw.cycling.then_some((raw.cycle_start, raw.cycle_end)),
            bar_start_beats: raw.bar_start_beats,
        }
    }
}

/// Owned metadata as the host reads it back from `manifest`.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Manifest {
    pub abi: u32,
    pub id: String,
    pub name: String,
    pub vendor: String,
    pub version: String,
    pub category: String,
    pub description: String,
    pub kind: Kind,
    pub params: Vec<ManifestParam>,
}
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ManifestParam {
    pub name: String,
    pub min: f64,
    pub max: f64,
    pub default: f64,
    pub unit: String,
    pub steps: u32,
    pub log: bool,
    pub labels: Vec<String>,
}
impl Manifest {
    pub fn of<P: Plugin>() -> Self {
        Self::from_parts(&P::INFO, &P::params())
    }
    pub fn from_parts(info: &Info, params: &[ParamSpec]) -> Self {
        Self {
            // The manifest format has not changed, and ABI 1 hosts refuse any other number.
            abi: BASE_ABI_VERSION,
            id: info.id.into(),
            name: info.name.into(),
            vendor: info.vendor.into(),
            version: info.version.into(),
            category: info.category.into(),
            description: info.description.into(),
            kind: info.kind,
            params: params
                .iter()
                .map(|p| ManifestParam {
                    name: p.name.into(),
                    min: p.min,
                    max: p.max,
                    default: p.default,
                    unit: p.unit.into(),
                    steps: p.steps,
                    log: p.log,
                    labels: p.labels.iter().map(|l| l.to_string()).collect(),
                })
                .collect(),
        }
    }
}

/// One plugin type. Instances are opaque pointers created by `create` and released by
/// `destroy`; buffers returned by `manifest` are released by `free_bytes`.
#[repr(C)]
pub struct PluginVTable {
    /// Writes the manifest JSON into a buffer the host frees with `free_bytes`. Returns 0.
    pub manifest: unsafe extern "C" fn(out: *mut *mut u8, len: *mut usize) -> i32,
    pub create: unsafe extern "C" fn(sample_rate: f64) -> *mut c_void,
    pub destroy: unsafe extern "C" fn(instance: *mut c_void),
    pub set_param: unsafe extern "C" fn(instance: *mut c_void, index: u32, value: f64),
    /// Audio thread. `audio` holds `frames` stereo frames; `notes` holds `note_count` events.
    pub process: unsafe extern "C" fn(
        instance: *mut c_void,
        audio: *mut [f32; 2],
        frames: u32,
        notes: *const NoteEvent,
        note_count: u32,
        ctx: *const RawContext,
    ),
    pub reset: unsafe extern "C" fn(instance: *mut c_void),
    pub latency: unsafe extern "C" fn(instance: *mut c_void) -> u32,
    pub free_bytes: unsafe extern "C" fn(ptr: *mut u8, len: usize),
}
// Vtables are tables of plain function pointers.
unsafe impl Sync for PluginVTable {}
unsafe impl Send for PluginVTable {}

/// The root of a plugin library.
#[repr(C)]
pub struct Entry {
    pub abi_version: u32,
    pub plugin_count: u32,
    pub plugin: unsafe extern "C" fn(index: u32) -> *const PluginVTable,
}
unsafe impl Sync for Entry {}
unsafe impl Send for Entry {}

/// The exported entry function's type, for hosts loading a library.
pub type EntryFn = unsafe extern "C" fn() -> *const Entry;

/// `process_events` result bit: `latency` now returns something else.
pub const FLAG_LATENCY_CHANGED: u32 = 1;

/// ABI 2: the ABI 1 table, then what was added. Never reorder; append and let `size` tell.
#[repr(C)]
pub struct PluginVTable2 {
    /// `size_of::<PluginVTable2>()` as the plugin was built. A host reads only what fits.
    pub size: u32,
    pub base: PluginVTable,
    /// Audio thread. `events` and `params` are sorted by frame, all frames `< frames`.
    /// Replaces `base.process` and block-start `set_param` for hosts that know ABI 2.
    pub process_events: unsafe extern "C" fn(
        instance: *mut c_void,
        audio: *mut [f32; 2],
        frames: u32,
        events: *const Event,
        event_count: u32,
        params: *const TimedParam,
        param_count: u32,
        ctx: *const RawContext,
    ) -> u32,
    /// Main thread, never on an instance that is processing. The buffer is released with
    /// `base.free_bytes`; an empty state leaves `*out` null. Returns 0 on success.
    pub save:
        unsafe extern "C" fn(instance: *mut c_void, out: *mut *mut u8, len: *mut usize) -> i32,
    /// Main thread, before the instance is handed to the audio thread. Returns 0 on success.
    pub load: unsafe extern "C" fn(instance: *mut c_void, bytes: *const u8, len: usize) -> i32,
    pub tail_seconds: unsafe extern "C" fn(instance: *mut c_void) -> f64,
}
unsafe impl Sync for PluginVTable2 {}
unsafe impl Send for PluginVTable2 {}

/// The root of a plugin library for ABI 2, behind `ondera_plugin_entry_v2`.
#[repr(C)]
pub struct Entry2 {
    pub abi_version: u32,
    pub plugin_count: u32,
    pub plugin: unsafe extern "C" fn(index: u32) -> *const PluginVTable2,
}
unsafe impl Sync for Entry2 {}
unsafe impl Send for Entry2 {}
pub type Entry2Fn = unsafe extern "C" fn() -> *const Entry2;

// ABI 1 is frozen: a change that moves any of these fails to compile.
const _: () = {
    use std::mem::{offset_of, size_of};
    let pointer = size_of::<usize>();
    assert!(size_of::<PluginVTable>() == 8 * pointer);
    assert!(offset_of!(PluginVTable, process) == 4 * pointer);
    assert!(offset_of!(PluginVTable, free_bytes) == 7 * pointer);
    assert!(offset_of!(Entry, plugin_count) == 4);
    assert!(offset_of!(Entry, plugin) == 8);
    assert!(size_of::<NoteEvent>() == 8);
    assert!(offset_of!(NoteEvent, on) == 4 && offset_of!(NoteEvent, channel) == 7);
    assert!(size_of::<RawContext>() == 72);
    assert!(offset_of!(RawContext, tempo) == 8);
    assert!(offset_of!(RawContext, numerator) == 40);
    assert!(offset_of!(RawContext, bar_start_beats) == 64);
    // ABI 2, frozen from here on as well.
    assert!(size_of::<Event>() == 12 && offset_of!(Event, bend) == 8);
    assert!(size_of::<TimedParam>() == 16 && offset_of!(TimedParam, value) == 8);
    assert!(offset_of!(PluginVTable2, base) == pointer);
    assert!(offset_of!(PluginVTable2, process_events) == 9 * pointer);
    assert!(size_of::<PluginVTable2>() == 13 * pointer);
};

unsafe fn give(bytes: Vec<u8>, out: *mut *mut u8, len: *mut usize) -> i32 {
    if out.is_null() || len.is_null() {
        return 1;
    }
    let boxed = bytes.into_boxed_slice();
    *len = boxed.len();
    *out = Box::into_raw(boxed) as *mut u8;
    0
}
unsafe extern "C" fn manifest<P: Plugin>(out: *mut *mut u8, len: *mut usize) -> i32 {
    let json = std::panic::catch_unwind(|| serde_json::to_vec(&Manifest::of::<P>()));
    match json {
        Ok(Ok(bytes)) => give(bytes, out, len),
        _ => 2,
    }
}
/// What an instance pointer really points at. A plugin that panics is poisoned: it is never
/// called again, an effect passes audio through and an instrument falls silent, and the host
/// keeps running. Unwinding out of an `extern "C"` function would abort the whole application.
struct Guarded<P> {
    plugin: P,
    poisoned: bool,
    /// What `latency` last answered, to notice when it changes.
    latency: u32,
}
impl<P> Guarded<P> {
    /// Run `f` on the plugin unless it is poisoned; a panic poisons it.
    fn run<T>(&mut self, fallback: T, f: impl FnOnce(&mut P) -> T) -> T {
        if self.poisoned {
            return fallback;
        }
        match std::panic::catch_unwind(AssertUnwindSafe(|| f(&mut self.plugin))) {
            Ok(value) => value,
            Err(_) => {
                self.poisoned = true;
                fallback
            }
        }
    }
}

unsafe extern "C" fn create<P: Plugin>(sample_rate: f64) -> *mut c_void {
    let rate = if sample_rate.is_finite() && sample_rate > 0.0 {
        sample_rate
    } else {
        48000.0
    };
    match std::panic::catch_unwind(|| {
        let plugin = P::new(rate);
        let latency = plugin.latency();
        Box::new(Guarded {
            plugin,
            poisoned: false,
            latency,
        })
    }) {
        Ok(plugin) => Box::into_raw(plugin) as *mut c_void,
        Err(_) => std::ptr::null_mut(),
    }
}
unsafe extern "C" fn destroy<P: Plugin>(instance: *mut c_void) {
    if !instance.is_null() {
        let _ = std::panic::catch_unwind(AssertUnwindSafe(|| {
            drop(Box::from_raw(instance as *mut Guarded<P>));
        }));
    }
}
unsafe extern "C" fn set_param<P: Plugin>(instance: *mut c_void, index: u32, value: f64) {
    if !instance.is_null() && value.is_finite() {
        (*(instance as *mut Guarded<P>)).run((), |p| p.set_param(index as usize, value));
    }
}
unsafe extern "C" fn process<P: Plugin>(
    instance: *mut c_void,
    audio: *mut [f32; 2],
    frames: u32,
    notes: *const NoteEvent,
    note_count: u32,
    ctx: *const RawContext,
) {
    if instance.is_null() || audio.is_null() || ctx.is_null() {
        return;
    }
    let audio = std::slice::from_raw_parts_mut(audio, frames as usize);
    let notes = if notes.is_null() || note_count == 0 {
        &[]
    } else {
        std::slice::from_raw_parts(notes, note_count as usize)
    };
    let ctx = ProcessContext::from(&*ctx);
    (*(instance as *mut Guarded<P>)).run((), |p| p.process(audio, notes, &ctx));
}
unsafe extern "C" fn reset<P: Plugin>(instance: *mut c_void) {
    if !instance.is_null() {
        (*(instance as *mut Guarded<P>)).run((), |p| p.reset());
    }
}
unsafe extern "C" fn latency<P: Plugin>(instance: *mut c_void) -> u32 {
    if instance.is_null() {
        0
    } else {
        (*(instance as *mut Guarded<P>)).run(0, |p| p.latency())
    }
}
unsafe extern "C" fn free_bytes(ptr: *mut u8, len: usize) {
    if !ptr.is_null() {
        drop(Box::from_raw(std::ptr::slice_from_raw_parts_mut(ptr, len)));
    }
}

unsafe fn slice<'a, T>(ptr: *const T, count: u32) -> &'a [T] {
    if ptr.is_null() || count == 0 {
        &[]
    } else {
        std::slice::from_raw_parts(ptr, count as usize)
    }
}
#[allow(clippy::too_many_arguments)]
unsafe extern "C" fn process_events<P: Plugin>(
    instance: *mut c_void,
    audio: *mut [f32; 2],
    frames: u32,
    events: *const Event,
    event_count: u32,
    params: *const TimedParam,
    param_count: u32,
    ctx: *const RawContext,
) -> u32 {
    if instance.is_null() || audio.is_null() || ctx.is_null() {
        return 0;
    }
    let audio = std::slice::from_raw_parts_mut(audio, frames as usize);
    let (events, params) = (slice(events, event_count), slice(params, param_count));
    let ctx = ProcessContext::from(&*ctx);
    let guarded = &mut *(instance as *mut Guarded<P>);
    let latency = guarded.run(guarded.latency, |p| {
        p.process_events(audio, events, params, &ctx);
        p.latency()
    });
    if latency == guarded.latency {
        0
    } else {
        guarded.latency = latency;
        FLAG_LATENCY_CHANGED
    }
}
unsafe extern "C" fn save<P: Plugin>(
    instance: *mut c_void,
    out: *mut *mut u8,
    len: *mut usize,
) -> i32 {
    if instance.is_null() || out.is_null() || len.is_null() {
        return 1;
    }
    *out = std::ptr::null_mut();
    *len = 0;
    match (*(instance as *mut Guarded<P>)).run(None, |p| Some(p.save())) {
        Some(bytes) if bytes.is_empty() => 0,
        Some(bytes) => give(bytes, out, len),
        None => 2,
    }
}
unsafe extern "C" fn load<P: Plugin>(instance: *mut c_void, bytes: *const u8, len: usize) -> i32 {
    if instance.is_null() || (bytes.is_null() && len > 0) {
        return 1;
    }
    let state = if len == 0 {
        &[]
    } else {
        std::slice::from_raw_parts(bytes, len)
    };
    match (*(instance as *mut Guarded<P>)).run(None, |p| Some(p.load(state))) {
        Some(Ok(())) => 0,
        Some(Err(_)) => 3,
        None => 2,
    }
}
unsafe extern "C" fn tail_seconds<P: Plugin>(instance: *mut c_void) -> f64 {
    if instance.is_null() {
        return 0.0;
    }
    let tail = (*(instance as *mut Guarded<P>)).run(0.0, |p| p.tail_seconds());
    if tail.is_nan() {
        0.0
    } else {
        tail.max(0.0)
    }
}

/// The ABI 2 vtable for one plugin type. Usable in `static` tables.
pub const fn vtable2<P: Plugin>() -> PluginVTable2 {
    PluginVTable2 {
        size: std::mem::size_of::<PluginVTable2>() as u32,
        base: vtable::<P>(),
        process_events: process_events::<P>,
        save: save::<P>,
        load: load::<P>,
        tail_seconds: tail_seconds::<P>,
    }
}
/// What a host may call in a table a library handed it: the table must be at least as large
/// as the ABI 2 this SDK knows.
///
/// # Safety
/// `table` must point at a `PluginVTable2` (or a later, longer revision of it).
pub unsafe fn checked_v2(table: *const PluginVTable2) -> Option<&'static PluginVTable2> {
    (!table.is_null() && (*table).size as usize >= std::mem::size_of::<PluginVTable2>())
        .then(|| &*table)
}

/// The vtable for one plugin type. Usable in `static` tables.
pub const fn vtable<P: Plugin>() -> PluginVTable {
    PluginVTable {
        manifest: manifest::<P>,
        create: create::<P>,
        destroy: destroy::<P>,
        set_param: set_param::<P>,
        process: process::<P>,
        reset: reset::<P>,
        latency: latency::<P>,
        free_bytes,
    }
}

/// Read a vtable's manifest on the host side.
///
/// # Safety
/// `table` must be a vtable produced by [`vtable`] or an ABI-compatible library.
pub unsafe fn read_manifest(table: &PluginVTable) -> Result<Manifest, String> {
    let mut ptr: *mut u8 = std::ptr::null_mut();
    let mut len = 0usize;
    let code = (table.manifest)(&mut ptr, &mut len);
    if code != 0 || ptr.is_null() {
        return Err(format!("Plugin manifest unavailable (code {code})"));
    }
    let bytes = std::slice::from_raw_parts(ptr, len).to_vec();
    (table.free_bytes)(ptr, len);
    let manifest: Manifest =
        serde_json::from_slice(&bytes).map_err(|e| format!("Invalid plugin manifest: {e}"))?;
    if !(BASE_ABI_VERSION..=ABI_VERSION).contains(&manifest.abi) {
        return Err(format!(
            "Plugin ABI {} is not supported (host ABI {BASE_ABI_VERSION} to {ABI_VERSION})",
            manifest.abi
        ));
    }
    if manifest.id.is_empty() || manifest.name.is_empty() {
        return Err("Plugin manifest lacks an id or name".into());
    }
    for p in &manifest.params {
        if !p.min.is_finite() || !p.max.is_finite() || p.min > p.max || !p.default.is_finite() {
            return Err(format!("Parameter `{}` has invalid bounds", p.name));
        }
    }
    Ok(manifest)
}
