//! The C ABI between Ondera and a plugin library.
//!
//! A library exports one symbol, `ondera_plugin_entry`, returning an [`Entry`] whose
//! `plugin(index)` hands out one [`PluginVTable`] per plugin type. Every function in the
//! vtable is generated by [`vtable`] from a [`Plugin`](crate::Plugin) implementation, so
//! plugin authors never write `extern "C"` themselves. The host treats the vtable as an
//! opaque contract: metadata as JSON, one instance pointer per instantiation, and
//! `process` on the audio thread.
//!
//! Hosts other than Ondera can consume the same ABI; the layout below is frozen for
//! `ABI_VERSION` 1.

use crate::{Info, Kind, NoteEvent, ParamSpec, Plugin, ProcessContext, ABI_VERSION};
use serde::{Deserialize, Serialize};
use std::{ffi::c_void, panic::AssertUnwindSafe};

/// Transport context in a layout that never changes.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct RawContext {
    pub playing: bool,
    pub recording: bool,
    pub cycling: bool,
    pub tempo: f64,
    pub position_beats: f64,
    pub position_seconds: f64,
    pub sample_time: i64,
    pub numerator: u32,
    pub denominator: u32,
    pub cycle_start: f64,
    pub cycle_end: f64,
    pub bar_start_beats: f64,
}
impl From<&ProcessContext> for RawContext {
    fn from(ctx: &ProcessContext) -> Self {
        let (cycle_start, cycle_end) = ctx.cycle.unwrap_or((0.0, 0.0));
        Self {
            playing: ctx.playing,
            recording: ctx.recording,
            cycling: ctx.cycle.is_some(),
            tempo: ctx.tempo,
            position_beats: ctx.position_beats,
            position_seconds: ctx.position_seconds,
            sample_time: ctx.sample_time,
            numerator: ctx.numerator,
            denominator: ctx.denominator,
            cycle_start,
            cycle_end,
            bar_start_beats: ctx.bar_start_beats,
        }
    }
}
impl From<&RawContext> for ProcessContext {
    fn from(raw: &RawContext) -> Self {
        Self {
            playing: raw.playing,
            recording: raw.recording,
            tempo: raw.tempo,
            position_beats: raw.position_beats,
            position_seconds: raw.position_seconds,
            sample_time: raw.sample_time,
            numerator: raw.numerator,
            denominator: raw.denominator,
            cycle: raw.cycling.then_some((raw.cycle_start, raw.cycle_end)),
            bar_start_beats: raw.bar_start_beats,
        }
    }
}

/// Owned metadata as the host reads it back from `manifest`.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Manifest {
    pub abi: u32,
    pub id: String,
    pub name: String,
    pub vendor: String,
    pub version: String,
    pub category: String,
    pub description: String,
    pub kind: Kind,
    pub params: Vec<ManifestParam>,
}
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct ManifestParam {
    pub name: String,
    pub min: f64,
    pub max: f64,
    pub default: f64,
    pub unit: String,
    pub steps: u32,
    pub log: bool,
    pub labels: Vec<String>,
}
impl Manifest {
    pub fn of<P: Plugin>() -> Self {
        Self::from_parts(&P::INFO, &P::params())
    }
    pub fn from_parts(info: &Info, params: &[ParamSpec]) -> Self {
        Self {
            abi: ABI_VERSION,
            id: info.id.into(),
            name: info.name.into(),
            vendor: info.vendor.into(),
            version: info.version.into(),
            category: info.category.into(),
            description: info.description.into(),
            kind: info.kind,
            params: params
                .iter()
                .map(|p| ManifestParam {
                    name: p.name.into(),
                    min: p.min,
                    max: p.max,
                    default: p.default,
                    unit: p.unit.into(),
                    steps: p.steps,
                    log: p.log,
                    labels: p.labels.iter().map(|l| l.to_string()).collect(),
                })
                .collect(),
        }
    }
}

/// One plugin type. Instances are opaque pointers created by `create` and released by
/// `destroy`; buffers returned by `manifest` are released by `free_bytes`.
#[repr(C)]
pub struct PluginVTable {
    /// Writes the manifest JSON into a buffer the host frees with `free_bytes`. Returns 0.
    pub manifest: unsafe extern "C" fn(out: *mut *mut u8, len: *mut usize) -> i32,
    pub create: unsafe extern "C" fn(sample_rate: f64) -> *mut c_void,
    pub destroy: unsafe extern "C" fn(instance: *mut c_void),
    pub set_param: unsafe extern "C" fn(instance: *mut c_void, index: u32, value: f64),
    /// Audio thread. `audio` holds `frames` stereo frames; `notes` holds `note_count` events.
    pub process: unsafe extern "C" fn(
        instance: *mut c_void,
        audio: *mut [f32; 2],
        frames: u32,
        notes: *const NoteEvent,
        note_count: u32,
        ctx: *const RawContext,
    ),
    pub reset: unsafe extern "C" fn(instance: *mut c_void),
    pub latency: unsafe extern "C" fn(instance: *mut c_void) -> u32,
    pub free_bytes: unsafe extern "C" fn(ptr: *mut u8, len: usize),
}
// Vtables are tables of plain function pointers.
unsafe impl Sync for PluginVTable {}
unsafe impl Send for PluginVTable {}

/// The root of a plugin library.
#[repr(C)]
pub struct Entry {
    pub abi_version: u32,
    pub plugin_count: u32,
    pub plugin: unsafe extern "C" fn(index: u32) -> *const PluginVTable,
}
unsafe impl Sync for Entry {}
unsafe impl Send for Entry {}

/// The exported entry function's type, for hosts loading a library.
pub type EntryFn = unsafe extern "C" fn() -> *const Entry;

unsafe fn give(bytes: Vec<u8>, out: *mut *mut u8, len: *mut usize) -> i32 {
    if out.is_null() || len.is_null() {
        return 1;
    }
    let boxed = bytes.into_boxed_slice();
    *len = boxed.len();
    *out = Box::into_raw(boxed) as *mut u8;
    0
}
unsafe extern "C" fn manifest<P: Plugin>(out: *mut *mut u8, len: *mut usize) -> i32 {
    let json = std::panic::catch_unwind(|| serde_json::to_vec(&Manifest::of::<P>()));
    match json {
        Ok(Ok(bytes)) => give(bytes, out, len),
        _ => 2,
    }
}
unsafe extern "C" fn create<P: Plugin>(sample_rate: f64) -> *mut c_void {
    let rate = if sample_rate.is_finite() && sample_rate > 0.0 {
        sample_rate
    } else {
        48000.0
    };
    match std::panic::catch_unwind(|| Box::new(P::new(rate))) {
        Ok(plugin) => Box::into_raw(plugin) as *mut c_void,
        Err(_) => std::ptr::null_mut(),
    }
}
unsafe extern "C" fn destroy<P: Plugin>(instance: *mut c_void) {
    if !instance.is_null() {
        let _ = std::panic::catch_unwind(AssertUnwindSafe(|| {
            drop(Box::from_raw(instance as *mut P));
        }));
    }
}
unsafe extern "C" fn set_param<P: Plugin>(instance: *mut c_void, index: u32, value: f64) {
    if !instance.is_null() && value.is_finite() {
        (*(instance as *mut P)).set_param(index as usize, value);
    }
}
unsafe extern "C" fn process<P: Plugin>(
    instance: *mut c_void,
    audio: *mut [f32; 2],
    frames: u32,
    notes: *const NoteEvent,
    note_count: u32,
    ctx: *const RawContext,
) {
    if instance.is_null() || audio.is_null() || ctx.is_null() {
        return;
    }
    let audio = std::slice::from_raw_parts_mut(audio, frames as usize);
    let notes = if notes.is_null() || note_count == 0 {
        &[]
    } else {
        std::slice::from_raw_parts(notes, note_count as usize)
    };
    let ctx = ProcessContext::from(&*ctx);
    (*(instance as *mut P)).process(audio, notes, &ctx);
}
unsafe extern "C" fn reset<P: Plugin>(instance: *mut c_void) {
    if !instance.is_null() {
        (*(instance as *mut P)).reset();
    }
}
unsafe extern "C" fn latency<P: Plugin>(instance: *mut c_void) -> u32 {
    if instance.is_null() {
        0
    } else {
        (*(instance as *mut P)).latency()
    }
}
unsafe extern "C" fn free_bytes(ptr: *mut u8, len: usize) {
    if !ptr.is_null() {
        drop(Box::from_raw(std::ptr::slice_from_raw_parts_mut(ptr, len)));
    }
}

/// The vtable for one plugin type. Usable in `static` tables.
pub const fn vtable<P: Plugin>() -> PluginVTable {
    PluginVTable {
        manifest: manifest::<P>,
        create: create::<P>,
        destroy: destroy::<P>,
        set_param: set_param::<P>,
        process: process::<P>,
        reset: reset::<P>,
        latency: latency::<P>,
        free_bytes,
    }
}

/// Read a vtable's manifest on the host side.
///
/// # Safety
/// `table` must be a vtable produced by [`vtable`] or an ABI-compatible library.
pub unsafe fn read_manifest(table: &PluginVTable) -> Result<Manifest, String> {
    let mut ptr: *mut u8 = std::ptr::null_mut();
    let mut len = 0usize;
    let code = (table.manifest)(&mut ptr, &mut len);
    if code != 0 || ptr.is_null() {
        return Err(format!("Plugin manifest unavailable (code {code})"));
    }
    let bytes = std::slice::from_raw_parts(ptr, len).to_vec();
    (table.free_bytes)(ptr, len);
    let manifest: Manifest =
        serde_json::from_slice(&bytes).map_err(|e| format!("Invalid plugin manifest: {e}"))?;
    if manifest.abi != ABI_VERSION {
        return Err(format!(
            "Plugin ABI {} is not supported (host ABI {ABI_VERSION})",
            manifest.abi
        ));
    }
    if manifest.id.is_empty() || manifest.name.is_empty() {
        return Err("Plugin manifest lacks an id or name".into());
    }
    for p in &manifest.params {
        if !p.min.is_finite() || !p.max.is_finite() || p.min > p.max || !p.default.is_finite() {
            return Err(format!("Parameter `{}` has invalid bounds", p.name));
        }
    }
    Ok(manifest)
}
