export * from './model/types';
export * from './model/time';
export * from './model/gain';
export { defaultStrip } from './model/strip';
export { TRACK_PALETTE } from './model/palette';
export type { Command, CommandDef, CommandCreator } from './commands/define';
export { CommandParamError, type ParamSchema, type ParamSpec, type ParamsOf } from './commands/schema';
export { ZOOM_MIN_PX_PER_BAR, ZOOM_MAX_PX_PER_BAR } from './commands/view';
export { commands, registry, getCommandDef, describeCommands } from './registry';
export { SessionStore, type Listener, type HistoryEntry } from './store';
export { NEUTRAL_LOG_COLOR } from './commands/agent';
export { INSERT_STATES } from './commands/strip';
export type { EngineClient } from './engine/EngineClient';
export { MockEngine, type MockEngineOptions } from './engine/MockEngine';
export { attachEngine } from './engine/attachEngine';
export { createMockSession } from './mock/session';
export { createEmptySession } from './mock/empty';
export { getPeaks, generatePeaks, PEAKS_PER_BAR } from './mock/waveform';
