//! The stock Ondera plugin library: twenty-three effects and eleven instruments written against
//! the `ondera-plugin` SDK. They are linked into the engine but served through the same C
//! ABI vtables as third-party native plugins, so the stock library doubles as the reference
//! implementation and a permanent test of the plugin path.

use crate::{
    dsp::*,
    host::native,
    plugin::{Descriptor, Format, Instance, ParamInfo},
};
use ondera_plugin::{
    ffi::{vtable2, Manifest, PluginVTable, PluginVTable2},
    plugin_table,
    prelude::*,
};
use std::{f64::consts::TAU, sync::LazyLock};

const VENDOR: &str = "Ondera";
const ON_OFF: &[&str] = &["Off", "On"];

fn category(name: &str) -> &'static str {
    match name {
        "Ondera Comp" | "Gate" | "Limiter" | "Transient" | "De-Esser" | "Pump" => "Dynamics",
        "Channel EQ" | "Filter" | "Auto Filter" => "EQ & Filter",
        "Tape Sat" | "Overdrive" | "Bitcrusher" | "Lo-Fi" => "Distortion",
        "Chorus" | "Phaser" | "Tremolo" | "Flanger" | "Auto Pan" => "Modulation",
        "Pitch Shift" => "Pitch",
        "Space" | "Echo" => "Space & Time",
        _ => "Utility",
    }
}

// ---------------------------------------------------------------------------
// Registry: one vtable per stock plugin, read back through the ABI.
// ---------------------------------------------------------------------------

static TABLES: [PluginVTable; 34] = plugin_table!(
    Synth,
    Piano,
    Drums,
    Sampler,
    Sub,
    Bell,
    Pad,
    RiserSynth,
    Comp,
    Eq,
    Saturator<false>,
    Chorus,
    Space,
    Echo,
    Gate,
    Limiter,
    Filter,
    Phaser,
    Tremolo,
    Bitcrusher,
    Width,
    Utility,
    Saturator<true>,
    Transient,
    Organ,
    Strings,
    AnalogBass,
    Flanger,
    AutoPan,
    AutoFilter,
    DeEsser,
    LoFi,
    PitchShift,
    Pump
);
/// The same plugins behind ABI 2. Instruments are created through these so they hear
/// controllers, pitch bend and pressure; effects stay on ABI 1, which needs no second
/// instance for state they do not have.
static TABLES_V2: [PluginVTable2; 34] = [
    vtable2::<Synth>(),
    vtable2::<Piano>(),
    vtable2::<Drums>(),
    vtable2::<Sampler>(),
    vtable2::<Sub>(),
    vtable2::<Bell>(),
    vtable2::<Pad>(),
    vtable2::<RiserSynth>(),
    vtable2::<Comp>(),
    vtable2::<Eq>(),
    vtable2::<Saturator<false>>(),
    vtable2::<Chorus>(),
    vtable2::<Space>(),
    vtable2::<Echo>(),
    vtable2::<Gate>(),
    vtable2::<Limiter>(),
    vtable2::<Filter>(),
    vtable2::<Phaser>(),
    vtable2::<Tremolo>(),
    vtable2::<Bitcrusher>(),
    vtable2::<Width>(),
    vtable2::<Utility>(),
    vtable2::<Saturator<true>>(),
    vtable2::<Transient>(),
    vtable2::<Organ>(),
    vtable2::<Strings>(),
    vtable2::<AnalogBass>(),
    vtable2::<Flanger>(),
    vtable2::<AutoPan>(),
    vtable2::<AutoFilter>(),
    vtable2::<DeEsser>(),
    vtable2::<LoFi>(),
    vtable2::<PitchShift>(),
    vtable2::<Pump>(),
];
static MANIFESTS: LazyLock<Vec<Manifest>> = LazyLock::new(|| {
    native::manifests(&TABLES).expect("Stock plugin manifests are generated by the SDK")
});
/// A stock plugin's one-line description ("Plate-style reverb with pre-delay…").
pub fn description(name: &str) -> Option<&'static str> {
    index_of(name).map(|i| MANIFESTS[i].description.as_str())
}
fn index_of(name: &str) -> Option<usize> {
    MANIFESTS.iter().position(|m| m.name == name)
}
/// The vtable table, for tests of the ABI path.
pub fn tables() -> &'static [PluginVTable] {
    &TABLES
}
pub fn is_stock(name: &str) -> bool {
    INSTRUMENTS.contains(&name) || EFFECTS.contains(&name)
}
pub fn descriptor(name: &str) -> Option<Descriptor> {
    let instrument = INSTRUMENTS.contains(&name);
    if !instrument && !EFFECTS.contains(&name) {
        return None;
    }
    Some(Descriptor {
        id: format!("stock:{name}"),
        format: Format::Stock,
        name: name.into(),
        vendor: VENDOR.into(),
        path: String::new(),
        instrument,
        effect: !instrument,
        category: if instrument {
            "Instrument".into()
        } else {
            category(name).into()
        },
    })
}
pub fn descriptors() -> Vec<Descriptor> {
    INSTRUMENTS
        .iter()
        .chain(EFFECTS.iter())
        .filter_map(|n| descriptor(n))
        .collect()
}
pub fn params(name: &str) -> Vec<ParamInfo> {
    index_of(name).map_or_else(Vec::new, |i| native::param_infos(&MANIFESTS[i]))
}
/// Instantiate a stock plugin with every parameter at its default.
pub fn create(name: &str, rate: u32) -> Option<Instance> {
    let index = index_of(name)?;
    let descriptor = descriptor(name)?;
    if descriptor.instrument {
        native::instance_from(&TABLES_V2[index], &MANIFESTS[index], descriptor, rate).ok()
    } else {
        native::instance_from(&TABLES[index], &MANIFESTS[index], descriptor, rate).ok()
    }
}

/// A factory preset: plugin name, preset name, parameter values by id.
pub type FactoryPreset = (&'static str, &'static str, &'static [(u32, f64)]);
/// Factory presets for the stock library.
pub const FACTORY_PRESETS: &[FactoryPreset] = &[
    (
        "Ondera Comp",
        "Vocal glue",
        &[(0, -22.0), (1, 3.0), (2, 8.0), (3, 90.0), (4, 3.0)],
    ),
    (
        "Ondera Comp",
        "Drum bus",
        &[
            (0, -14.0),
            (1, 4.0),
            (2, 25.0),
            (3, 60.0),
            (4, 2.0),
            (5, 60.0),
        ],
    ),
    (
        "Ondera Comp",
        "Bass tighten",
        &[(0, -20.0), (1, 6.0), (2, 4.0), (3, 150.0), (4, 4.0)],
    ),
    (
        "Channel EQ",
        "Air and body",
        &[
            (0, 2.0),
            (1, 110.0),
            (2, -1.5),
            (3, 400.0),
            (5, 3.0),
            (6, 9000.0),
        ],
    ),
    (
        "Channel EQ",
        "Telephone",
        &[
            (0, -15.0),
            (1, 400.0),
            (2, 6.0),
            (3, 1800.0),
            (4, 1.2),
            (5, -15.0),
            (6, 3000.0),
        ],
    ),
    (
        "Space",
        "Small room",
        &[(0, 25.0), (1, 60.0), (2, 4.0), (4, 18.0)],
    ),
    (
        "Space",
        "Cathedral",
        &[(0, 95.0), (1, 20.0), (2, 40.0), (3, 100.0), (4, 40.0)],
    ),
    (
        "Echo",
        "Dotted eighth",
        &[(0, 4.0), (2, 45.0), (3, 4000.0), (4, 1.0), (5, 30.0)],
    ),
    (
        "Echo",
        "Slapback",
        &[(0, 0.0), (1, 110.0), (2, 8.0), (3, 8000.0), (5, 25.0)],
    ),
    ("Tape Sat", "Warm", &[(0, 4.0), (1, 7000.0), (3, -1.0)]),
    ("Tape Sat", "Crushed", &[(0, 18.0), (1, 4000.0), (3, -6.0)]),
    (
        "Filter",
        "Telephone band",
        &[(0, 2.0), (1, 1200.0), (2, 35.0)],
    ),
    (
        "Filter",
        "Dub low-pass",
        &[(0, 0.0), (1, 400.0), (2, 55.0), (3, 6.0)],
    ),
    (
        "Chorus",
        "Wide ensemble",
        &[(0, 0.35), (1, 70.0), (2, 90.0), (3, 60.0)],
    ),
    ("Limiter", "Master safe", &[(0, 2.0), (1, -1.0), (2, 120.0)]),
    (
        "Ondera Synth",
        "Soft square lead",
        &[
            (0, 1.0),
            (1, 1800.0),
            (2, 60.0),
            (3, 12.0),
            (4, 400.0),
            (5, 45.0),
            (6, 300.0),
        ],
    ),
    (
        "Ondera Synth",
        "Plucky bass",
        &[
            (0, 0.0),
            (1, 900.0),
            (2, 85.0),
            (3, 2.0),
            (4, 120.0),
            (5, 10.0),
            (6, 120.0),
        ],
    ),
    (
        "Choir Pad",
        "Slow bloom",
        &[(0, 900.0), (1, 14.0), (2, 1200.0), (3, 2500.0)],
    ),
];

// ---------------------------------------------------------------------------
// Instruments: one voice engine, eight presets, eight plugin types.
// ---------------------------------------------------------------------------

fn instrument_specs(preset: Preset) -> Vec<ParamSpec> {
    let d = InstrumentParams::for_preset(preset);
    let mut specs = vec![];
    match preset {
        Preset::Bass => {
            specs.push(hz("Cutoff", 60.0, 8000.0, d.cutoff));
            specs.push(param("Env Amount", 0.0, 100.0, d.env_amount * 100.0, "%"));
            specs.push(param("Decay", 5.0, 3000.0, d.decay * 1000.0, "ms"));
            specs.push(param("Sustain", 0.0, 100.0, d.sustain * 100.0, "%"));
            specs.push(param("Release", 10.0, 5000.0, d.release * 1000.0, "ms"));
        }
        Preset::Synth => {
            specs.push(choice("Wave", &["Saw", "Square", "Triangle"], 0));
            specs.push(hz("Cutoff", 100.0, 16000.0, d.cutoff));
            specs.push(param("Env Amount", 0.0, 100.0, d.env_amount * 100.0, "%"));
            specs.push(param("Attack", 1.0, 3000.0, d.attack * 1000.0, "ms"));
            specs.push(param("Decay", 5.0, 3000.0, d.decay * 1000.0, "ms"));
            specs.push(param("Sustain", 0.0, 100.0, d.sustain * 100.0, "%"));
            specs.push(param("Release", 10.0, 5000.0, d.release * 1000.0, "ms"));
        }
        Preset::Pad | Preset::Strings => {
            specs.push(hz("Cutoff", 100.0, 16000.0, d.cutoff));
            specs.push(param("Detune", 0.0, 50.0, d.detune, "ct"));
            specs.push(param("Attack", 1.0, 3000.0, d.attack * 1000.0, "ms"));
            specs.push(param("Release", 10.0, 5000.0, d.release * 1000.0, "ms"));
        }
        Preset::Drums => {}
        _ => {
            specs.push(param("Attack", 1.0, 3000.0, d.attack * 1000.0, "ms"));
            specs.push(param("Release", 10.0, 5000.0, d.release * 1000.0, "ms"));
        }
    }
    specs.push(param("Level", -24.0, 6.0, 0.0, "dB"));
    specs
}

const VOICES: usize = 32;
/// Pitch-bend range of the stock instruments, in semitones either way.
const BEND_SEMITONES: f64 = 2.0;
struct StockInstrument {
    preset: Preset,
    params: InstrumentParams,
    voices: [Option<Voice>; VOICES],
    /// Voices whose key is up while the sustain pedal (CC64) holds them.
    sustained: [bool; VOICES],
    pedal: bool,
    modulation: f64,
    pressure: f64,
    serial: u64,
    rate: f64,
    order: Vec<&'static str>,
}
impl StockInstrument {
    fn new(preset: Preset, rate: f64) -> Self {
        Self {
            preset,
            params: InstrumentParams::for_preset(preset),
            voices: [None; VOICES],
            sustained: [false; VOICES],
            pedal: false,
            modulation: 0.0,
            pressure: 0.0,
            serial: 0,
            rate,
            order: instrument_specs(preset).iter().map(|s| s.name).collect(),
        }
    }
    fn note_on(&mut self, pitch: u8, velocity: u8) {
        self.serial += 1;
        let voice = Voice::new(self.preset, pitch, velocity, self.serial);
        if let Some(slot) = self.voices.iter().position(|v| v.is_none()) {
            self.voices[slot] = Some(voice);
            self.sustained[slot] = false;
            return;
        }
        // Steal the oldest released voice, else the oldest voice.
        let victim = self
            .voices
            .iter()
            .enumerate()
            .filter_map(|(i, v)| v.map(|v| (i, v)))
            .min_by(|a, b| (a.1.held(), a.1.serial).cmp(&(b.1.held(), b.1.serial)))
            .map(|(i, _)| i)
            .unwrap_or(0);
        self.voices[victim] = Some(voice);
        self.sustained[victim] = false;
    }
    fn note_off(&mut self, pitch: u8) {
        let sustained = &self.sustained;
        if let Some((slot, _)) = self
            .voices
            .iter()
            .enumerate()
            .filter_map(|(i, v)| v.map(|v| (i, v)))
            .filter(|(i, v)| v.pitch == pitch && v.held() && !sustained[*i])
            .max_by_key(|(_, v)| v.serial)
        {
            if self.pedal {
                self.sustained[slot] = true;
            } else if let Some(v) = &mut self.voices[slot] {
                v.release();
            }
        }
    }
    fn set_pedal(&mut self, down: bool) {
        self.pedal = down;
        if !down {
            for (slot, voice) in self.voices.iter_mut().enumerate() {
                if std::mem::take(&mut self.sustained[slot]) {
                    if let Some(v) = voice {
                        v.release();
                    }
                }
            }
        }
    }
    /// Notes, sustain (CC64), mod wheel (CC1, vibrato), pressure (vibrato too), pitch bend
    /// (two semitones) and the channel-mode messages. Other controllers are ignored.
    fn apply(&mut self, e: Event) {
        match e.kind {
            event::NOTE_ON if e.value > 0 => self.note_on(e.key, e.value),
            event::NOTE_ON | event::NOTE_OFF => self.note_off(e.key),
            event::CONTROL => match e.key {
                1 => self.modulation = e.value.min(127) as f64 / 127.0,
                64 => self.set_pedal(e.value >= 64),
                120 => {
                    self.voices = [None; VOICES];
                    self.sustained = [false; VOICES];
                }
                121 => {
                    self.modulation = 0.0;
                    self.pressure = 0.0;
                    self.params.pitch_ratio = 1.0;
                    self.set_pedal(false);
                }
                123 => {
                    self.set_pedal(false);
                    for v in self.voices.iter_mut().flatten() {
                        v.release();
                    }
                }
                _ => {}
            },
            event::PITCH_BEND => {
                self.params.pitch_ratio = 2f64.powf(e.bend_amount() as f64 * BEND_SEMITONES / 12.0)
            }
            event::CHANNEL_PRESSURE => self.pressure = e.value.min(127) as f64 / 127.0,
            _ => {}
        }
        self.params.vibrato = self.modulation.max(self.pressure);
    }
    fn set(&mut self, index: usize, value: f64) {
        let Some(name) = self.order.get(index) else {
            return;
        };
        let p = &mut self.params;
        match *name {
            "Wave" => p.wave = value.round() as u8,
            "Cutoff" => p.cutoff = value,
            "Env Amount" => p.env_amount = value / 100.0,
            "Attack" => p.attack = value / 1000.0,
            "Decay" => p.decay = value / 1000.0,
            "Sustain" => p.sustain = value / 100.0,
            "Release" => p.release = value / 1000.0,
            "Detune" => p.detune = value,
            "Level" => p.level = db_to_gain(value),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.voices = [None; VOICES];
        self.sustained = [false; VOICES];
        self.pedal = false;
        self.modulation = 0.0;
        self.pressure = 0.0;
        self.params.pitch_ratio = 1.0;
        self.params.vibrato = 0.0;
    }
    /// Render with events and parameter changes applied at their frames. Both are sorted.
    fn process<E: Copy + Into<Event>>(
        &mut self,
        audio: &mut [[f32; 2]],
        events: &[E],
        params: &[TimedParam],
    ) {
        let (mut next, mut next_param) = (0, 0);
        for (i, frame) in audio.iter_mut().enumerate() {
            while let Some(change) = params.get(next_param).filter(|c| c.frame as usize <= i) {
                if change.value.is_finite() {
                    self.set(change.index as usize, change.value);
                }
                next_param += 1;
            }
            while let Some(event) = events
                .get(next)
                .map(|e| (*e).into())
                .filter(|e: &Event| e.frame as usize <= i)
            {
                self.apply(event);
                next += 1;
            }
            let mut sum = 0.0;
            for (slot, voice) in self.voices.iter_mut().enumerate() {
                if let Some(v) = voice {
                    sum += v.sample(&self.params, self.rate);
                    if v.finished(&self.params) {
                        *voice = None;
                        self.sustained[slot] = false;
                    }
                }
            }
            if !sum.is_finite() {
                sum = 0.0;
            }
            frame[0] += sum;
            frame[1] += sum;
        }
        // Anything scheduled at the block end.
        for change in &params[next_param..] {
            if change.value.is_finite() {
                self.set(change.index as usize, change.value);
            }
        }
        for event in &events[next..] {
            self.apply((*event).into());
        }
    }
}
macro_rules! instrument {
    ($ty:ident, $preset:expr, $id:literal, $name:literal, $doc:literal) => {
        pub struct $ty(StockInstrument);
        impl Plugin for $ty {
            const INFO: Info = Info::instrument($id, $name, VENDOR).describe($doc);
            fn params() -> Vec<ParamSpec> {
                instrument_specs($preset)
            }
            fn new(rate: f64) -> Self {
                Self(StockInstrument::new($preset, rate))
            }
            fn set_param(&mut self, index: usize, value: f64) {
                self.0.set(index, value)
            }
            fn reset(&mut self) {
                self.0.reset()
            }
            fn process(&mut self, audio: &mut [[f32; 2]], notes: &[NoteEvent], _: &ProcessContext) {
                self.0.process(audio, notes, &[])
            }
            fn process_events(
                &mut self,
                audio: &mut [[f32; 2]],
                events: &[Event],
                params: &[TimedParam],
                _: &ProcessContext,
            ) {
                self.0.process(audio, events, params)
            }
        }
    };
}
instrument!(
    Synth,
    Preset::Synth,
    "org.ondera.stock.synth",
    "Ondera Synth",
    "Subtractive synth with three waves, a filter envelope and ADSR."
);
instrument!(
    Piano,
    Preset::Piano,
    "org.ondera.stock.epiano",
    "E-Piano Mk I",
    "Tine electric piano with velocity-sensitive bark."
);
instrument!(
    Drums,
    Preset::Drums,
    "org.ondera.stock.drums",
    "Drum Machine",
    "Analogue-style kick, snare and hats on general MIDI pitches."
);
instrument!(
    Sampler,
    Preset::Pluck,
    "org.ondera.stock.sampler",
    "Sampler",
    "Short plucked tone."
);
instrument!(
    Sub,
    Preset::Sub,
    "org.ondera.stock.sub808",
    "Sub Bass 808",
    "Pure sine sub with a quick pitch settle."
);
instrument!(
    Bell,
    Preset::Bell,
    "org.ondera.stock.glasskeys",
    "Glass Keys",
    "FM bell keys with a long shimmer."
);
instrument!(
    Pad,
    Preset::Pad,
    "org.ondera.stock.choirpad",
    "Choir Pad",
    "Detuned saw pad with a soft low-pass."
);
instrument!(
    RiserSynth,
    Preset::Riser,
    "org.ondera.stock.riser",
    "Riser",
    "Filtered noise that rises over four seconds."
);
instrument!(
    Organ,
    Preset::Organ,
    "org.ondera.stock.organ",
    "Tonewheel Organ",
    "Five-drawbar tonewheel organ with key click."
);
instrument!(
    Strings,
    Preset::Strings,
    "org.ondera.stock.strings",
    "String Ensemble",
    "Three detuned saws with slow vibrato behind a low-pass, for string pads and swells."
);
instrument!(
    AnalogBass,
    Preset::Bass,
    "org.ondera.stock.analogbass",
    "Analog Bass",
    "Saw over a sub-octave square through an enveloped filter and a soft clip."
);

// ---------------------------------------------------------------------------
// Effects
// ---------------------------------------------------------------------------

/// One-pole smoothing for a continuous effect parameter, so automation that arrives every
/// `render::AUTOMATION_GRAIN` frames becomes a curve instead of a staircase. Values set
/// before the first processed sample, after `new` or `snap`, are taken at once: a freshly
/// loaded plugin or a locate does not glide from the defaults. Discrete parameters (modes,
/// switches, sync divisions) are never smoothed.
#[derive(Clone, Copy, Debug)]
struct Smoothed {
    current: f64,
    target: f64,
    coefficient: f64,
    live: bool,
}
impl Smoothed {
    /// Time constant: long enough to hide a 32-frame step, short enough to follow a hand.
    const SECONDS: f64 = 0.01;
    /// Relative distance at which the value lands on its target exactly, so a settled
    /// parameter gives bit-identical output to one that never moved.
    const SETTLE: f64 = 1e-4;
    fn new(rate: f64, value: f64) -> Self {
        Self {
            current: value,
            target: value,
            coefficient: 1.0 - (-1.0 / (rate.max(1.0) * Self::SECONDS)).exp(),
            live: false,
        }
    }
    fn set(&mut self, value: f64) {
        self.target = value;
        if !self.live {
            self.current = value;
        }
    }
    /// Jump to the target; the next `set` before processing is taken at once too.
    fn snap(&mut self) {
        self.current = self.target;
        self.live = false;
    }
    /// One sample on; true while the value is still moving.
    #[inline]
    fn advance(&mut self) -> bool {
        self.live = true;
        if self.current == self.target {
            return false;
        }
        let next = self.current + self.coefficient * (self.target - self.current);
        self.current = if (self.target - next).abs() <= Self::SETTLE * self.target.abs().max(1.0) {
            self.target
        } else {
            next
        };
        true
    }
    /// One sample on, and the value for that sample.
    #[inline]
    fn next(&mut self) -> f64 {
        self.advance();
        self.current
    }
    #[inline]
    fn value(&self) -> f64 {
        self.current
    }
}

/// Filter coefficients from smoothed values, recomputed every `GRAIN` samples while they
/// move rather than on every sample: a sixteenth of the `tan()` and `exp()` calls.
#[derive(Default)]
struct Retune {
    tick: u32,
    stale: bool,
}
impl Retune {
    const GRAIN: u32 = 16;
    /// A value was set: recompute before the next sample.
    fn mark(&mut self) {
        self.stale = true;
        self.tick = 0;
    }
    /// Whether to recompute before this sample, given whether any input moved.
    #[inline]
    fn due(&mut self, moved: bool) -> bool {
        self.stale |= moved;
        let due = self.tick == 0 && self.stale;
        self.tick = (self.tick + 1) % Self::GRAIN;
        if due {
            self.stale = false;
        }
        due
    }
}

pub struct Comp {
    rate: f64,
    threshold: Smoothed,
    ratio: Smoothed,
    attack: f32,
    release: f32,
    makeup: Smoothed,
    mix: Smoothed,
    env: f32,
}
impl Plugin for Comp {
    const INFO: Info = Info::effect("org.ondera.stock.comp", "Ondera Comp", VENDOR, "Dynamics")
        .describe("Feed-forward peak compressor with makeup and parallel mix.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Threshold", -60.0, 0.0, -18.0, "dB"),
            param("Ratio", 1.0, 20.0, 4.0, ":1"),
            param("Attack", 0.1, 100.0, 10.0, "ms"),
            param("Release", 10.0, 1000.0, 120.0, "ms"),
            param("Makeup", 0.0, 24.0, 0.0, "dB"),
            param("Mix", 0.0, 100.0, 100.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            threshold: Smoothed::new(rate, -18.0),
            ratio: Smoothed::new(rate, 4.0),
            attack: coef(rate, 0.01),
            release: coef(rate, 0.12),
            makeup: Smoothed::new(rate, 1.0),
            mix: Smoothed::new(rate, 1.0),
            env: 0.0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.threshold.set(value),
            1 => self.ratio.set(value.max(1.0)),
            2 => self.attack = coef(self.rate, value / 1000.0),
            3 => self.release = coef(self.rate, value / 1000.0),
            4 => self.makeup.set(db_to_gain(value) as f64),
            5 => self.mix.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.env = 0.0;
        for s in [
            &mut self.threshold,
            &mut self.ratio,
            &mut self.makeup,
            &mut self.mix,
        ] {
            s.snap();
        }
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let threshold = self.threshold.next() as f32;
            let ratio = self.ratio.next() as f32;
            let makeup = self.makeup.next() as f32;
            let mix = self.mix.next() as f32;
            let peak = frame[0].abs().max(frame[1].abs());
            let over = (db(peak) - threshold).max(0.0);
            let target = over * (1.0 - 1.0 / ratio);
            let c = if target > self.env {
                self.attack
            } else {
                self.release
            };
            self.env += c * (target - self.env);
            let gain = db_to_gain(-self.env as f64) * makeup;
            for s in frame.iter_mut() {
                *s = *s * (1.0 - mix) + *s * gain * mix;
            }
        }
    }
}

pub struct Eq {
    rate: f64,
    values: [Smoothed; 7],
    bands: [Biquad; 3],
    retune: Retune,
}
impl Eq {
    fn update(&mut self) {
        let v = self.values.map(|s| s.value());
        self.bands[0].low_shelf(self.rate, v[1], v[0]);
        self.bands[1].peaking(self.rate, v[3], v[2], v[4]);
        self.bands[2].high_shelf(self.rate, v[6], v[5]);
    }
}
impl Plugin for Eq {
    const INFO: Info = Info::effect("org.ondera.stock.eq", "Channel EQ", VENDOR, "EQ & Filter")
        .describe("Low shelf, peaking mid and high shelf.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Low Gain", -15.0, 15.0, 1.5, "dB"),
            hz("Low Freq", 40.0, 500.0, 120.0),
            param("Mid Gain", -15.0, 15.0, -2.0, "dB"),
            hz("Mid Freq", 200.0, 8000.0, 1000.0),
            param("Mid Q", 0.3, 5.0, 0.8, ""),
            param("High Gain", -15.0, 15.0, 2.0, "dB"),
            hz("High Freq", 2000.0, 16000.0, 6000.0),
        ]
    }
    fn new(rate: f64) -> Self {
        let mut retune = Retune::default();
        retune.mark();
        Self {
            rate,
            values: [1.5, 120.0, -2.0, 1000.0, 0.8, 2.0, 6000.0].map(|v| Smoothed::new(rate, v)),
            bands: [Biquad::default(); 3],
            retune,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        if let Some(v) = self.values.get_mut(index) {
            v.set(value);
            self.retune.mark();
        }
    }
    fn reset(&mut self) {
        self.bands.iter_mut().for_each(Biquad::clear);
        self.values.iter_mut().for_each(Smoothed::snap);
        self.retune.mark();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let mut moved = false;
            for v in &mut self.values {
                moved |= v.advance();
            }
            if self.retune.due(moved) {
                self.update();
            }
            for (c, s) in frame.iter_mut().enumerate() {
                let mut x = *s;
                for band in &mut self.bands {
                    x = band.process(c, x);
                }
                *s = x;
            }
        }
    }
}

/// `HARD` selects the overdrive curve; `false` is the tape saturator.
pub struct Saturator<const HARD: bool> {
    rate: f64,
    drive: Smoothed,
    /// Output normalisation for the drive, smoothed with it.
    norm: Smoothed,
    tone: Smoothed,
    mix: Smoothed,
    output: Smoothed,
    lp: [f32; 2],
}
impl<const HARD: bool> Saturator<HARD> {
    fn norm(drive: f32) -> f64 {
        (1.0 / drive.max(1.0).powf(0.6)) as f64
    }
    fn build(rate: f64, drive_db: f64, tone_hz: f64, output_db: f64) -> Self {
        let drive = db_to_gain(drive_db);
        Self {
            rate,
            drive: Smoothed::new(rate, drive as f64),
            norm: Smoothed::new(rate, Self::norm(drive)),
            tone: Smoothed::new(rate, coef(rate, 1.0 / (TAU * tone_hz)) as f64),
            mix: Smoothed::new(rate, 1.0),
            output: Smoothed::new(rate, db_to_gain(output_db) as f64),
            lp: [0.0; 2],
        }
    }
    fn set(&mut self, index: usize, value: f64) {
        match index {
            0 => {
                let drive = db_to_gain(value);
                self.drive.set(drive as f64);
                self.norm.set(Self::norm(drive));
            }
            1 => self
                .tone
                .set(coef(self.rate, 1.0 / (TAU * value.max(20.0))) as f64),
            2 => self.mix.set(value / 100.0),
            3 => self.output.set(db_to_gain(value) as f64),
            _ => {}
        }
    }
    fn clear(&mut self) {
        self.lp = [0.0; 2];
        for s in [
            &mut self.drive,
            &mut self.norm,
            &mut self.tone,
            &mut self.mix,
            &mut self.output,
        ] {
            s.snap();
        }
    }
    fn run(&mut self, audio: &mut [[f32; 2]]) {
        for frame in audio {
            let drive = self.drive.next() as f32;
            let norm = self.norm.next() as f32;
            let tone = self.tone.next() as f32;
            let mix = self.mix.next() as f32;
            let output = self.output.next() as f32;
            for (c, s) in frame.iter_mut().enumerate() {
                let pre = *s * drive;
                let shaped = if HARD {
                    pre / (1.0 + pre.abs())
                } else {
                    pre.tanh()
                } * norm;
                self.lp[c] += tone * (shaped - self.lp[c]);
                let wet = self.lp[c] * output;
                *s = *s * (1.0 - mix) + wet * mix;
            }
        }
    }
}
impl Plugin for Saturator<false> {
    const INFO: Info = Info::effect("org.ondera.stock.tapesat", "Tape Sat", VENDOR, "Distortion")
        .describe("Soft tape-style saturation with a tone control.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Drive", 0.0, 24.0, 6.0, "dB"),
            hz("Tone", 1000.0, 20000.0, 9000.0),
            param("Mix", 0.0, 100.0, 100.0, "%"),
            param("Output", -24.0, 6.0, -2.0, "dB"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self::build(rate, 6.0, 9000.0, -2.0)
    }
    fn set_param(&mut self, index: usize, value: f64) {
        self.set(index, value)
    }
    fn reset(&mut self) {
        self.clear();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        self.run(audio)
    }
}
impl Plugin for Saturator<true> {
    const INFO: Info = Info::effect(
        "org.ondera.stock.overdrive",
        "Overdrive",
        VENDOR,
        "Distortion",
    )
    .describe("Harder clipping curve for leads and drums.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Drive", 0.0, 40.0, 12.0, "dB"),
            hz("Tone", 500.0, 12000.0, 4000.0),
            param("Mix", 0.0, 100.0, 100.0, "%"),
            param("Output", -24.0, 6.0, -6.0, "dB"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self::build(rate, 12.0, 4000.0, -6.0)
    }
    fn set_param(&mut self, index: usize, value: f64) {
        self.set(index, value)
    }
    fn reset(&mut self) {
        self.clear();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        self.run(audio)
    }
}

pub struct Chorus {
    rate: f64,
    delay: Delay,
    phase: f64,
    speed: f64,
    depth: Smoothed,
    spread: Smoothed,
    mix: Smoothed,
}
impl Plugin for Chorus {
    const INFO: Info = Info::effect("org.ondera.stock.chorus", "Chorus", VENDOR, "Modulation")
        .describe("Two modulated delay taps with stereo spread.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Rate", 0.05, 5.0, 0.6, "Hz"),
            param("Depth", 0.0, 100.0, 40.0, "%"),
            param("Spread", 0.0, 100.0, 50.0, "%"),
            param("Mix", 0.0, 100.0, 50.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            delay: Delay::new(0.06, rate as u32),
            phase: 0.0,
            speed: 0.6,
            depth: Smoothed::new(rate, 0.4),
            spread: Smoothed::new(rate, 0.5),
            mix: Smoothed::new(rate, 0.5),
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            // The rate moves the LFO's speed, not its phase: nothing to smooth.
            0 => self.speed = value,
            1 => self.depth.set(value / 100.0),
            2 => self.spread.set(value / 100.0),
            3 => self.mix.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.delay.clear();
        for s in [&mut self.depth, &mut self.spread, &mut self.mix] {
            s.snap();
        }
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        let r = self.rate;
        for frame in audio {
            let depth = self.depth.next();
            let spread = self.spread.next();
            let mix = self.mix.next() as f32;
            self.phase = (self.phase + self.speed / r).fract();
            let base = 0.016;
            let swing = 0.008 * depth;
            let l = self
                .delay
                .read((base + swing * (TAU * self.phase).sin()) * r);
            let ph = (self.phase + 0.5 * spread).fract();
            let rr = self.delay.read((base + swing * (TAU * ph).sin()) * r);
            self.delay.write(*frame);
            frame[0] += l[0] * mix;
            frame[1] += rr[1] * mix;
        }
    }
}

struct Comb {
    buffer: Vec<f32>,
    index: usize,
    store: f32,
}
impl Comb {
    fn new(len: usize) -> Self {
        Self {
            buffer: vec![0.0; len.max(1)],
            index: 0,
            store: 0.0,
        }
    }
    #[inline]
    fn process(&mut self, input: f32, feedback: f32, damp: f32) -> f32 {
        let out = self.buffer[self.index];
        self.store = out * (1.0 - damp) + self.store * damp;
        let next = input + self.store * feedback;
        self.buffer[self.index] = if next.is_finite() { next } else { 0.0 };
        self.index = (self.index + 1) % self.buffer.len();
        out
    }
}
struct Allpass {
    buffer: Vec<f32>,
    index: usize,
}
impl Allpass {
    fn new(len: usize) -> Self {
        Self {
            buffer: vec![0.0; len.max(1)],
            index: 0,
        }
    }
    #[inline]
    fn process(&mut self, input: f32) -> f32 {
        let buffered = self.buffer[self.index];
        let out = -input + buffered;
        self.buffer[self.index] = input + buffered * 0.5;
        self.index = (self.index + 1) % self.buffer.len();
        out
    }
}
/// A Freeverb-style reverb: eight combs and four allpasses per channel.
pub struct Space {
    combs: [Vec<Comb>; 2],
    allpasses: [Vec<Allpass>; 2],
    predelay: Delay,
    rate: f64,
    feedback: Smoothed,
    damp: Smoothed,
    pre: Smoothed,
    width: Smoothed,
    mix: Smoothed,
}
impl Plugin for Space {
    const INFO: Info = Info::effect("org.ondera.stock.space", "Space", VENDOR, "Space & Time")
        .describe("Plate-style reverb with pre-delay, damping and width.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Size", 0.0, 100.0, 55.0, "%"),
            param("Damp", 0.0, 100.0, 40.0, "%"),
            param("Pre-delay", 0.0, 100.0, 10.0, "ms"),
            param("Width", 0.0, 100.0, 100.0, "%"),
            param("Mix", 0.0, 100.0, 30.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        let scale = rate / 44100.0;
        let tune = |n: usize, offset: usize| ((n + offset) as f64 * scale) as usize;
        let combs = |offset| {
            [1116, 1188, 1277, 1356, 1422, 1491, 1557, 1617]
                .iter()
                .map(|&n| Comb::new(tune(n, offset)))
                .collect()
        };
        let allpasses = |offset| {
            [556, 441, 341, 225]
                .iter()
                .map(|&n| Allpass::new(tune(n, offset)))
                .collect()
        };
        Self {
            combs: [combs(0), combs(23)],
            allpasses: [allpasses(0), allpasses(23)],
            predelay: Delay::new(0.11, rate as u32),
            rate,
            feedback: Smoothed::new(rate, (0.7 + 0.28 * 0.55f32) as f64),
            damp: Smoothed::new(rate, (0.4 * 0.4f32) as f64),
            pre: Smoothed::new(rate, 0.01),
            width: Smoothed::new(rate, 1.0),
            mix: Smoothed::new(rate, 0.3f32 as f64),
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.feedback.set(0.7 + 0.28 * value / 100.0),
            1 => self.damp.set(0.4 * value / 100.0),
            2 => self.pre.set(value / 1000.0),
            3 => self.width.set(value / 100.0),
            4 => self.mix.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        for c in self.combs.iter_mut().flatten() {
            c.buffer.fill(0.0);
            c.store = 0.0;
        }
        for a in self.allpasses.iter_mut().flatten() {
            a.buffer.fill(0.0);
        }
        self.predelay.clear();
        for s in [
            &mut self.feedback,
            &mut self.damp,
            &mut self.pre,
            &mut self.width,
            &mut self.mix,
        ] {
            s.snap();
        }
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let feedback = self.feedback.next() as f32;
            let damp = self.damp.next() as f32;
            let pre = self.pre.next() * self.rate;
            let width = self.width.next() as f32;
            let mix = self.mix.next() as f32;
            let wet1 = mix * (width / 2.0 + 0.5);
            let wet2 = mix * ((1.0 - width) / 2.0);
            let delayed = self.predelay.read(pre);
            self.predelay.write(*frame);
            let input = (delayed[0] + delayed[1]) * 0.015;
            let mut out = [0.0f32; 2];
            for (c, out_c) in out.iter_mut().enumerate() {
                let mut acc = 0.0;
                for comb in &mut self.combs[c] {
                    acc += comb.process(input, feedback, damp);
                }
                for ap in &mut self.allpasses[c] {
                    acc = ap.process(acc);
                }
                *out_c = acc;
            }
            frame[0] += out[0] * wet1 + out[1] * wet2;
            frame[1] += out[1] * wet1 + out[0] * wet2;
        }
    }
}

pub struct Echo {
    rate: f64,
    lines: [Delay; 2],
    sync: usize,
    time_ms: f64,
    feedback: Smoothed,
    tone: Smoothed,
    pingpong: bool,
    mix: Smoothed,
    lp: [f32; 2],
    current: f64,
}
impl Echo {
    fn seconds(&self, tempo: f64) -> f64 {
        let beat = 60.0 / tempo.max(20.0);
        match self.sync {
            1 => beat / 4.0,
            2 => beat / 3.0,
            3 => beat / 2.0,
            4 => beat * 0.75,
            5 => beat,
            6 => beat * 1.5,
            7 => beat * 2.0,
            _ => self.time_ms / 1000.0,
        }
        .clamp(0.005, 2.0)
    }
}
impl Plugin for Echo {
    const INFO: Info = Info::effect("org.ondera.stock.echo", "Echo", VENDOR, "Space & Time")
        .describe("Tempo-synced stereo delay with ping-pong and tone.");
    fn params() -> Vec<ParamSpec> {
        vec![
            choice(
                "Sync",
                &["Free", "1/16", "1/8T", "1/8", "1/8.", "1/4", "1/4.", "1/2"],
                3,
            ),
            param("Time", 10.0, 2000.0, 375.0, "ms"),
            param("Feedback", 0.0, 95.0, 35.0, "%"),
            hz("Tone", 500.0, 20000.0, 6000.0),
            choice("Ping-pong", ON_OFF, 0),
            param("Mix", 0.0, 100.0, 35.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            lines: [Delay::new(2.1, rate as u32), Delay::new(2.1, rate as u32)],
            sync: 3,
            time_ms: 375.0,
            feedback: Smoothed::new(rate, 0.35),
            tone: Smoothed::new(rate, coef(rate, 1.0 / (TAU * 6000.0)) as f64),
            pingpong: false,
            mix: Smoothed::new(rate, 0.35),
            lp: [0.0; 2],
            current: 0.0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.sync = value.round().max(0.0) as usize,
            // The delay time already glides towards its target in `process`.
            1 => self.time_ms = value,
            2 => self.feedback.set(value / 100.0),
            3 => self
                .tone
                .set(coef(self.rate, 1.0 / (TAU * value.max(20.0))) as f64),
            4 => self.pingpong = value >= 0.5,
            5 => self.mix.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.lines.iter_mut().for_each(Delay::clear);
        self.lp = [0.0; 2];
        for s in [&mut self.feedback, &mut self.tone, &mut self.mix] {
            s.snap();
        }
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], ctx: &ProcessContext) {
        let target = self.seconds(ctx.tempo) * self.rate;
        if self.current == 0.0 {
            self.current = target;
        }
        let glide = coef(self.rate, 0.05) as f64;
        for frame in audio {
            let feedback = self.feedback.next() as f32;
            let tone = self.tone.next() as f32;
            let mix = self.mix.next() as f32;
            self.current += glide * (target - self.current);
            let l = self.lines[0].read(self.current)[0];
            let r = self.lines[1].read(self.current)[1];
            self.lp[0] += tone * (l - self.lp[0]);
            self.lp[1] += tone * (r - self.lp[1]);
            let (fl, fr) = (self.lp[0] * feedback, self.lp[1] * feedback);
            if self.pingpong {
                let mono = (frame[0] + frame[1]) * 0.5;
                self.lines[0].write([mono + fr, 0.0]);
                self.lines[1].write([0.0, fl]);
            } else {
                self.lines[0].write([frame[0] + fl, 0.0]);
                self.lines[1].write([0.0, frame[1] + fr]);
            }
            frame[0] += l * mix;
            frame[1] += r * mix;
        }
    }
}

pub struct Gate {
    rate: f64,
    threshold: Smoothed,
    attack: f32,
    hold: u32,
    release: f32,
    range: Smoothed,
    env: f32,
    gain: f32,
    held: u32,
}
impl Plugin for Gate {
    const INFO: Info = Info::effect("org.ondera.stock.gate", "Gate", VENDOR, "Dynamics")
        .describe("Noise gate with hold and range.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Threshold", -80.0, 0.0, -40.0, "dB"),
            param("Attack", 0.1, 50.0, 1.0, "ms"),
            param("Hold", 0.0, 500.0, 50.0, "ms"),
            param("Release", 5.0, 1000.0, 100.0, "ms"),
            param("Range", -80.0, 0.0, -80.0, "dB"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            threshold: Smoothed::new(rate, db_to_gain(-40.0) as f64),
            attack: coef(rate, 0.001),
            hold: (rate * 0.05) as u32,
            release: coef(rate, 0.1),
            range: Smoothed::new(rate, 0.0001f32 as f64),
            env: 0.0,
            gain: 0.0,
            held: 0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.threshold.set(db_to_gain(value) as f64),
            1 => self.attack = coef(self.rate, value / 1000.0),
            2 => self.hold = (self.rate * value / 1000.0) as u32,
            3 => self.release = coef(self.rate, value / 1000.0),
            4 => self.range.set(db_to_gain(value) as f64),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.env = 0.0;
        self.gain = 0.0;
        self.threshold.snap();
        self.range.snap();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        let follow = coef(self.rate, 0.0005);
        let decay = coef(self.rate, 0.02);
        for frame in audio {
            let threshold = self.threshold.next() as f32;
            let range = self.range.next() as f32;
            let peak = frame[0].abs().max(frame[1].abs());
            self.env += if peak > self.env { follow } else { decay } * (peak - self.env);
            let open = if self.env > threshold {
                self.held = self.hold;
                true
            } else if self.held > 0 {
                self.held -= 1;
                true
            } else {
                false
            };
            let target = if open { 1.0 } else { range };
            let c = if target > self.gain {
                self.attack
            } else {
                self.release
            };
            self.gain += c * (target - self.gain);
            frame[0] *= self.gain;
            frame[1] *= self.gain;
        }
    }
}

pub struct Limiter {
    rate: f64,
    input: Smoothed,
    ceiling: Smoothed,
    release: f32,
    delay: Delay,
    lookahead: usize,
    gain: f32,
}
impl Plugin for Limiter {
    const INFO: Info = Info::effect("org.ondera.stock.limiter", "Limiter", VENDOR, "Dynamics")
        .describe("Look-ahead brickwall limiter.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Input", 0.0, 24.0, 0.0, "dB"),
            param("Ceiling", -20.0, 0.0, -0.3, "dB"),
            param("Release", 10.0, 1000.0, 80.0, "ms"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            input: Smoothed::new(rate, 1.0),
            ceiling: Smoothed::new(rate, db_to_gain(-0.3) as f64),
            release: coef(rate, 0.08),
            delay: Delay::new(0.002, rate as u32),
            lookahead: (rate as u32 / 1000).max(1) as usize,
            gain: 1.0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.input.set(db_to_gain(value) as f64),
            1 => self.ceiling.set(db_to_gain(value) as f64),
            2 => self.release = coef(self.rate, value / 1000.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.delay.clear();
        self.gain = 1.0;
        self.input.snap();
        self.ceiling.snap();
    }
    fn latency(&self) -> u32 {
        self.lookahead as u32
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let input = self.input.next() as f32;
            let ceiling = self.ceiling.next() as f32;
            let x = [frame[0] * input, frame[1] * input];
            let peak = x[0].abs().max(x[1].abs());
            let needed = if peak > ceiling { ceiling / peak } else { 1.0 };
            if needed < self.gain {
                self.gain = needed;
            } else {
                self.gain += self.release * (needed - self.gain);
            }
            let delayed = self.delay.read(self.lookahead as f64);
            self.delay.write(x);
            frame[0] = (delayed[0] * self.gain).clamp(-ceiling, ceiling);
            frame[1] = (delayed[1] * self.gain).clamp(-ceiling, ceiling);
        }
    }
}

pub struct Filter {
    rate: f64,
    kind: u8,
    cutoff: Smoothed,
    resonance: Smoothed,
    drive: Smoothed,
    svf: Svf,
    retune: Retune,
}
impl Filter {
    fn tune(&mut self) {
        self.svf
            .set(self.rate, self.cutoff.value(), self.resonance.value());
    }
}
impl Plugin for Filter {
    const INFO: Info = Info::effect("org.ondera.stock.filter", "Filter", VENDOR, "EQ & Filter")
        .describe("State variable filter with resonance and drive.");
    fn params() -> Vec<ParamSpec> {
        vec![
            choice("Type", &["Low-pass", "High-pass", "Band-pass"], 0),
            hz("Cutoff", 20.0, 20000.0, 1000.0),
            param("Resonance", 0.0, 100.0, 20.0, "%"),
            param("Drive", 0.0, 24.0, 0.0, "dB"),
        ]
    }
    fn new(rate: f64) -> Self {
        let mut f = Self {
            rate,
            kind: 0,
            cutoff: Smoothed::new(rate, 1000.0),
            resonance: Smoothed::new(rate, 0.2),
            drive: Smoothed::new(rate, 1.0),
            svf: Svf::default(),
            retune: Retune::default(),
        };
        f.tune();
        f
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.kind = value.round() as u8,
            1 => self.cutoff.set(value),
            2 => self.resonance.set(value / 100.0),
            3 => self.drive.set(db_to_gain(value) as f64),
            _ => {}
        }
        self.retune.mark();
    }
    fn reset(&mut self) {
        self.svf.clear();
        for s in [&mut self.cutoff, &mut self.resonance, &mut self.drive] {
            s.snap();
        }
        self.retune.mark();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let moved = self.cutoff.advance() | self.resonance.advance();
            if self.retune.due(moved) {
                self.tune();
            }
            let drive = self.drive.next() as f32;
            for (c, s) in frame.iter_mut().enumerate() {
                let x = if drive > 1.0 { (*s * drive).tanh() } else { *s };
                let (lp, bp, hp) = self.svf.process(c, x);
                *s = match self.kind {
                    1 => hp,
                    2 => bp,
                    _ => lp,
                };
            }
        }
    }
}

pub struct Phaser {
    rate: f64,
    speed: f64,
    depth: Smoothed,
    stages: usize,
    feedback: Smoothed,
    center: Smoothed,
    mix: Smoothed,
    phase: f64,
    state: [[f32; 2]; 12],
    last: [f32; 2],
}
impl Plugin for Phaser {
    const INFO: Info = Info::effect("org.ondera.stock.phaser", "Phaser", VENDOR, "Modulation")
        .describe("Two to twelve all-pass stages swept by an LFO.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Rate", 0.02, 5.0, 0.3, "Hz"),
            param("Depth", 0.0, 100.0, 70.0, "%"),
            choice("Stages", &["2", "4", "6", "8", "10", "12"], 2),
            param("Feedback", -90.0, 90.0, 30.0, "%"),
            hz("Center", 200.0, 4000.0, 800.0),
            param("Mix", 0.0, 100.0, 50.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            speed: 0.3,
            depth: Smoothed::new(rate, 0.7),
            stages: 6,
            feedback: Smoothed::new(rate, 0.3),
            center: Smoothed::new(rate, 800.0),
            mix: Smoothed::new(rate, 0.5),
            phase: 0.0,
            state: [[0.0; 2]; 12],
            last: [0.0; 2],
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.speed = value,
            1 => self.depth.set(value / 100.0),
            2 => self.stages = ((value.round() as usize + 1) * 2).clamp(2, 12),
            3 => self.feedback.set(value / 100.0),
            4 => self.center.set(value),
            5 => self.mix.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.state = [[0.0; 2]; 12];
        self.last = [0.0; 2];
        for s in [
            &mut self.depth,
            &mut self.feedback,
            &mut self.center,
            &mut self.mix,
        ] {
            s.snap();
        }
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let depth = self.depth.next();
            let feedback = self.feedback.next() as f32;
            let center = self.center.next();
            let mix = self.mix.next() as f32;
            self.phase = (self.phase + self.speed / self.rate).fract();
            let lfo = (TAU * self.phase).sin();
            let hz = (center * 2f64.powf(lfo * depth * 2.0)).clamp(20.0, self.rate * 0.45);
            let w = (std::f64::consts::PI * hz / self.rate).tan();
            let c = ((1.0 - w) / (1.0 + w)) as f32;
            for ch in 0..2 {
                let mut x = frame[ch] + self.last[ch] * feedback;
                for stage in 0..self.stages {
                    let z = &mut self.state[stage][ch];
                    let y = -c * x + *z;
                    *z = x + c * y;
                    x = y;
                }
                if !x.is_finite() {
                    x = 0.0;
                    self.state.iter_mut().for_each(|s| s[ch] = 0.0);
                }
                self.last[ch] = x;
                frame[ch] = frame[ch] * (1.0 - mix) + x * mix;
            }
        }
    }
}

pub struct Tremolo {
    rate: f64,
    speed: f64,
    depth: Smoothed,
    shape: u8,
    stereo: Smoothed,
    phase: f64,
}
impl Tremolo {
    fn wave(&self, phase: f64) -> f32 {
        let v = match self.shape {
            1 => triangle(phase),
            2 => {
                if phase < 0.5 {
                    1.0
                } else {
                    -1.0
                }
            }
            _ => (TAU * phase).sin(),
        };
        ((v + 1.0) * 0.5) as f32
    }
}
impl Plugin for Tremolo {
    const INFO: Info = Info::effect("org.ondera.stock.tremolo", "Tremolo", VENDOR, "Modulation")
        .describe("Amplitude modulation with three shapes and stereo phase.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Rate", 0.1, 20.0, 4.0, "Hz"),
            param("Depth", 0.0, 100.0, 60.0, "%"),
            choice("Shape", &["Sine", "Triangle", "Square"], 0),
            param("Stereo", 0.0, 180.0, 0.0, "°"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            speed: 4.0,
            depth: Smoothed::new(rate, 0.6),
            shape: 0,
            stereo: Smoothed::new(rate, 0.0),
            phase: 0.0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.speed = value,
            1 => self.depth.set(value / 100.0),
            2 => self.shape = value.round() as u8,
            3 => self.stereo.set(value / 360.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.depth.snap();
        self.stereo.snap();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let depth = self.depth.next() as f32;
            let stereo = self.stereo.next();
            self.phase = (self.phase + self.speed / self.rate).fract();
            let l = 1.0 - depth * (1.0 - self.wave(self.phase));
            let r = 1.0 - depth * (1.0 - self.wave((self.phase + stereo).fract()));
            frame[0] *= l;
            frame[1] *= r;
        }
    }
}

pub struct Bitcrusher {
    bits: Smoothed,
    factor: u32,
    mix: Smoothed,
    counter: u32,
    held: [f32; 2],
}
impl Bitcrusher {
    fn step(bits: f64) -> f32 {
        2f32.powf(bits.max(1.0) as f32 - 1.0)
    }
}
impl Plugin for Bitcrusher {
    const INFO: Info = Info::effect(
        "org.ondera.stock.bitcrusher",
        "Bitcrusher",
        VENDOR,
        "Distortion",
    )
    .describe("Bit depth and sample rate reduction.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Bits", 2.0, 16.0, 8.0, "bit"),
            param("Downsample", 1.0, 64.0, 4.0, "x"),
            param("Mix", 0.0, 100.0, 100.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            bits: Smoothed::new(rate, 8.0),
            factor: 4,
            mix: Smoothed::new(rate, 1.0),
            counter: 0,
            held: [0.0; 2],
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.bits.set(value as f32 as f64),
            // A whole number of samples to hold: a step, not a sweep.
            1 => self.factor = value.round().max(1.0) as u32,
            2 => self.mix.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.bits.snap();
        self.mix.snap();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        let mut step = Self::step(self.bits.value());
        for frame in audio {
            if self.bits.advance() {
                step = Self::step(self.bits.value());
            }
            let mix = self.mix.next() as f32;
            if self.counter == 0 {
                self.held = frame.map(|s| (s * step).round() / step);
            }
            self.counter = (self.counter + 1) % self.factor.max(1);
            for (c, s) in frame.iter_mut().enumerate() {
                *s = *s * (1.0 - mix) + self.held[c] * mix;
            }
        }
    }
}

pub struct Width {
    rate: f64,
    width: Smoothed,
    bass: f32,
    lp: f32,
}
impl Plugin for Width {
    const INFO: Info = Info::effect("org.ondera.stock.width", "Stereo Width", VENDOR, "Utility")
        .describe("Mid/side width with optional mono bass.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Width", 0.0, 200.0, 120.0, "%"),
            param("Bass Mono", 0.0, 500.0, 0.0, "Hz"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            width: Smoothed::new(rate, 1.2),
            bass: 0.0,
            lp: 0.0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.width.set(value / 100.0),
            // A crossover on the side signal: moving it in steps is inaudible, and gliding it
            // through zero would leave the filter's last output behind as an offset.
            1 => {
                self.bass = if value < 1.0 {
                    0.0
                } else {
                    coef(self.rate, 1.0 / (TAU * value))
                }
            }
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.width.snap();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let width = self.width.next() as f32;
            let mid = (frame[0] + frame[1]) * 0.5;
            let mut side = (frame[0] - frame[1]) * 0.5;
            if self.bass > 0.0 {
                self.lp += self.bass * (side - self.lp);
                side -= self.lp;
            }
            side *= width;
            frame[0] = mid + side;
            frame[1] = mid - side;
        }
    }
}

pub struct Utility {
    gain: Smoothed,
    pan: Smoothed,
    invert: [bool; 2],
    mono: bool,
}
impl Utility {
    /// Left and right gains of the pan law.
    fn law(pan: f64) -> (f32, f32) {
        let pan = pan as f32;
        ((1.0 - pan.max(0.0)).sqrt(), (1.0 + pan.min(0.0)).sqrt())
    }
}
impl Plugin for Utility {
    const INFO: Info = Info::effect("org.ondera.stock.utility", "Utility", VENDOR, "Utility")
        .describe("Gain, pan, polarity and mono fold-down.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Gain", -60.0, 12.0, 0.0, "dB"),
            param("Pan", -100.0, 100.0, 0.0, ""),
            choice("Invert L", ON_OFF, 0),
            choice("Invert R", ON_OFF, 0),
            choice("Mono", ON_OFF, 0),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            gain: Smoothed::new(rate, 1.0),
            pan: Smoothed::new(rate, 0.0),
            invert: [false; 2],
            mono: false,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.gain.set(db_to_gain(value) as f64),
            1 => self.pan.set((value / 100.0) as f32 as f64),
            2 => self.invert[0] = value >= 0.5,
            3 => self.invert[1] = value >= 0.5,
            4 => self.mono = value >= 0.5,
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.gain.snap();
        self.pan.snap();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        let (mut left, mut right) = Self::law(self.pan.value());
        for frame in audio {
            if self.pan.advance() {
                (left, right) = Self::law(self.pan.value());
            }
            let gain = self.gain.next() as f32;
            if self.mono {
                let m = (frame[0] + frame[1]) * 0.5;
                *frame = [m, m];
            }
            for (c, s) in frame.iter_mut().enumerate() {
                if self.invert[c] {
                    *s = -*s;
                }
            }
            frame[0] *= gain * left;
            frame[1] *= gain * right;
        }
    }
}

pub struct Transient {
    rate: f64,
    attack: Smoothed,
    sustain: Smoothed,
    fast: f32,
    slow: f32,
}
impl Plugin for Transient {
    const INFO: Info = Info::effect(
        "org.ondera.stock.transient",
        "Transient",
        VENDOR,
        "Dynamics",
    )
    .describe("Attack and sustain shaping from a two-speed envelope difference.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Attack", -100.0, 100.0, 30.0, "%"),
            param("Sustain", -100.0, 100.0, 0.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            attack: Smoothed::new(rate, 0.3),
            sustain: Smoothed::new(rate, 0.0),
            fast: 0.0,
            slow: 0.0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.attack.set(value / 100.0),
            1 => self.sustain.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.fast = 0.0;
        self.slow = 0.0;
        self.attack.snap();
        self.sustain.snap();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        let fast_up = coef(self.rate, 0.0005);
        let fast_down = coef(self.rate, 0.02);
        let slow_up = coef(self.rate, 0.02);
        let slow_down = coef(self.rate, 0.15);
        for frame in audio {
            let attack = self.attack.next() as f32;
            let sustain = self.sustain.next() as f32;
            let peak = frame[0].abs().max(frame[1].abs());
            self.fast += if peak > self.fast { fast_up } else { fast_down } * (peak - self.fast);
            self.slow += if peak > self.slow { slow_up } else { slow_down } * (peak - self.slow);
            let diff = db(self.fast) - db(self.slow);
            let attack_db = attack * diff.clamp(0.0, 24.0);
            let sustain_db = sustain * (-diff).clamp(0.0, 24.0);
            let gain = db_to_gain((attack_db + sustain_db) as f64).clamp(0.05, 8.0);
            frame[0] *= gain;
            frame[1] *= gain;
        }
    }
}

// ---------------------------------------------------------------------------
// Second shelf: movement, de-essing, wear, pitch and tempo-locked pumping.
// ---------------------------------------------------------------------------

pub struct Flanger {
    rate: f64,
    delay: Delay,
    speed: f64,
    depth: Smoothed,
    manual: Smoothed,
    feedback: Smoothed,
    mix: Smoothed,
    phase: f64,
}
impl Plugin for Flanger {
    const INFO: Info = Info::effect("org.ondera.stock.flanger", "Flanger", VENDOR, "Modulation")
        .describe("A short swept delay with feedback: jet sweeps to metallic resonance.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Rate", 0.02, 8.0, 0.35, "Hz"),
            param("Depth", 0.0, 100.0, 70.0, "%"),
            param("Manual", 0.2, 10.0, 2.5, "ms"),
            param("Feedback", -95.0, 95.0, 55.0, "%"),
            param("Mix", 0.0, 100.0, 50.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            delay: Delay::new(0.03, rate as u32),
            speed: 0.35,
            depth: Smoothed::new(rate, 0.7),
            manual: Smoothed::new(rate, 2.5),
            feedback: Smoothed::new(rate, 0.55),
            mix: Smoothed::new(rate, 0.5),
            phase: 0.0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.speed = value,
            1 => self.depth.set(value / 100.0),
            2 => self.manual.set(value),
            3 => self.feedback.set(value / 100.0),
            4 => self.mix.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.delay.clear();
        for s in [
            &mut self.depth,
            &mut self.manual,
            &mut self.feedback,
            &mut self.mix,
        ] {
            s.snap();
        }
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let depth = self.depth.next();
            let manual = self.manual.next();
            let feedback = self.feedback.next() as f32;
            let mix = self.mix.next() as f32;
            self.phase = (self.phase + self.speed / self.rate).fract();
            let sweep = 0.5 + 0.5 * (TAU * self.phase).sin();
            let ms = manual * (1.0 - depth) + (0.2 + manual * 2.0 * sweep) * depth;
            let wet = self.delay.read(ms.clamp(0.1, 25.0) / 1000.0 * self.rate);
            self.delay.write([
                (frame[0] + wet[0] * feedback).clamp(-4.0, 4.0),
                (frame[1] + wet[1] * feedback).clamp(-4.0, 4.0),
            ]);
            frame[0] += wet[0] * mix;
            frame[1] += wet[1] * mix;
        }
    }
}

pub struct AutoPan {
    rate: f64,
    speed: f64,
    depth: Smoothed,
    shape: u8,
    phase: f64,
}
impl Plugin for AutoPan {
    const INFO: Info = Info::effect("org.ondera.stock.autopan", "Auto Pan", VENDOR, "Modulation")
        .describe("Moves the signal between the speakers at constant power.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Rate", 0.05, 12.0, 1.0, "Hz"),
            param("Depth", 0.0, 100.0, 80.0, "%"),
            choice("Shape", &["Sine", "Triangle", "Square"], 0),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            speed: 1.0,
            depth: Smoothed::new(rate, 0.8),
            shape: 0,
            phase: 0.0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.speed = value,
            1 => self.depth.set(value / 100.0),
            2 => self.shape = value.round() as u8,
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.depth.snap();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let depth = self.depth.next() as f32;
            self.phase = (self.phase + self.speed / self.rate).fract();
            let lfo = match self.shape {
                1 => triangle(self.phase),
                2 => {
                    if self.phase < 0.5 {
                        1.0
                    } else {
                        -1.0
                    }
                }
                _ => (TAU * self.phase).sin(),
            } as f32;
            // Constant-power pan law around the centre.
            let angle = (lfo * depth + 1.0) * std::f32::consts::FRAC_PI_4;
            let mono = (frame[0] + frame[1]) * 0.5;
            let side = (frame[0] - frame[1]) * 0.5 * (1.0 - depth);
            frame[0] = mono * angle.cos() * std::f32::consts::SQRT_2 + side;
            frame[1] = mono * angle.sin() * std::f32::consts::SQRT_2 - side;
        }
    }
}

pub struct AutoFilter {
    rate: f64,
    svf: Svf,
    cutoff: Smoothed,
    resonance: Smoothed,
    speed: f64,
    lfo_depth: Smoothed,
    env_depth: Smoothed,
    phase: f64,
    envelope: f32,
    tick: u32,
}
impl Plugin for AutoFilter {
    const INFO: Info = Info::effect(
        "org.ondera.stock.autofilter",
        "Auto Filter",
        VENDOR,
        "EQ & Filter",
    )
    .describe("A resonant low-pass moved by an LFO and by how loud the signal is.");
    fn params() -> Vec<ParamSpec> {
        vec![
            hz("Cutoff", 40.0, 16000.0, 600.0),
            param("Resonance", 0.0, 100.0, 45.0, "%"),
            param("LFO Rate", 0.02, 12.0, 0.5, "Hz"),
            param("LFO Depth", 0.0, 100.0, 40.0, "%"),
            param("Envelope", -100.0, 100.0, 40.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            svf: Svf::default(),
            cutoff: Smoothed::new(rate, 600.0),
            resonance: Smoothed::new(rate, 0.45),
            speed: 0.5,
            lfo_depth: Smoothed::new(rate, 0.4),
            env_depth: Smoothed::new(rate, 0.4),
            phase: 0.0,
            envelope: 0.0,
            tick: 0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.cutoff.set(value),
            1 => self.resonance.set(value / 100.0),
            2 => self.speed = value,
            3 => self.lfo_depth.set(value / 100.0),
            4 => self.env_depth.set(value / 100.0),
            _ => {}
        }
        self.tick = 0;
    }
    fn reset(&mut self) {
        self.svf.clear();
        self.envelope = 0.0;
        for s in [
            &mut self.cutoff,
            &mut self.resonance,
            &mut self.lfo_depth,
            &mut self.env_depth,
        ] {
            s.snap();
        }
        self.tick = 0;
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        let (up, down) = (coef(self.rate, 0.004), coef(self.rate, 0.18));
        for frame in audio {
            self.phase = (self.phase + self.speed / self.rate).fract();
            let level = frame[0].abs().max(frame[1].abs());
            self.envelope +=
                if level > self.envelope { up } else { down } * (level - self.envelope);
            for s in [
                &mut self.cutoff,
                &mut self.resonance,
                &mut self.lfo_depth,
                &mut self.env_depth,
            ] {
                s.advance();
            }
            // Coefficients every 16 samples: inaudible, and a sixteenth of the tan() calls.
            if self.tick == 0 {
                let octaves = (TAU * self.phase).sin() * self.lfo_depth.value() * 3.0
                    + (self.envelope.min(1.0) as f64).sqrt() * self.env_depth.value() * 5.0;
                self.svf.set(
                    self.rate,
                    self.cutoff.value() * 2f64.powf(octaves),
                    self.resonance.value(),
                );
            }
            self.tick = (self.tick + 1) % Retune::GRAIN;
            frame[0] = self.svf.process(0, frame[0]).0;
            frame[1] = self.svf.process(1, frame[1]).0;
        }
    }
}

pub struct DeEsser {
    rate: f64,
    detect: Biquad,
    split: Biquad,
    frequency: Smoothed,
    threshold: Smoothed,
    range: Smoothed,
    listen: bool,
    envelope: f32,
    retune: Retune,
}
impl DeEsser {
    fn tune(&mut self) {
        let frequency = self.frequency.value();
        self.detect.highpass(self.rate, frequency, 0.9);
        self.split.highpass(self.rate, frequency * 0.8, 0.707);
    }
}
impl Plugin for DeEsser {
    const INFO: Info = Info::effect("org.ondera.stock.deesser", "De-Esser", VENDOR, "Dynamics")
        .describe("Turns down only the harsh band of a voice, only while it is harsh.");
    fn params() -> Vec<ParamSpec> {
        vec![
            hz("Frequency", 2000.0, 12000.0, 6500.0),
            param("Threshold", -60.0, 0.0, -28.0, "dB"),
            param("Range", 0.0, 24.0, 9.0, "dB"),
            switch("Listen", false),
        ]
    }
    fn new(rate: f64) -> Self {
        let mut retune = Retune::default();
        retune.mark();
        Self {
            rate,
            detect: Biquad::default(),
            split: Biquad::default(),
            frequency: Smoothed::new(rate, 6500.0),
            threshold: Smoothed::new(rate, -28.0),
            range: Smoothed::new(rate, 9.0),
            listen: false,
            envelope: 0.0,
            retune,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => {
                self.frequency.set(value);
                self.retune.mark();
            }
            1 => self.threshold.set(value as f32 as f64),
            2 => self.range.set(value as f32 as f64),
            3 => self.listen = value >= 0.5,
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.detect.clear();
        self.split.clear();
        self.envelope = 0.0;
        for s in [&mut self.frequency, &mut self.threshold, &mut self.range] {
            s.snap();
        }
        self.retune.mark();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        let (up, down) = (coef(self.rate, 0.001), coef(self.rate, 0.06));
        for frame in audio {
            let moved = self.frequency.advance();
            if self.retune.due(moved) {
                self.tune();
            }
            let threshold = self.threshold.next() as f32;
            let range = self.range.next() as f32;
            let side = self.detect.process(0, (frame[0] + frame[1]) * 0.5).abs();
            self.envelope += if side > self.envelope { up } else { down } * (side - self.envelope);
            let over = (db(self.envelope) - threshold).max(0.0);
            let gain = db_to_gain(-(over * 0.75).min(range) as f64);
            let high = [
                self.split.process(0, frame[0]),
                self.split.process(1, frame[1]),
            ];
            if self.listen {
                *frame = high;
            } else {
                frame[0] -= high[0] * (1.0 - gain);
                frame[1] -= high[1] * (1.0 - gain);
            }
        }
    }
}

pub struct LoFi {
    rate: f64,
    delay: Delay,
    tone: Biquad,
    wobble: Smoothed,
    noise: Smoothed,
    cutoff: Smoothed,
    drive: Smoothed,
    mix: Smoothed,
    phase: f64,
    flutter: f64,
    seed: u32,
    hiss: f32,
    /// Input level: the hiss rides on the programme so silence stays silent.
    presence: f32,
    retune: Retune,
}
impl Plugin for LoFi {
    const INFO: Info = Info::effect("org.ondera.stock.lofi", "Lo-Fi", VENDOR, "Distortion")
        .describe("Worn tape and dusty vinyl: pitch wobble, hiss, a dull top and a little crunch.");
    fn params() -> Vec<ParamSpec> {
        vec![
            param("Wobble", 0.0, 100.0, 35.0, "%"),
            param("Noise", 0.0, 100.0, 20.0, "%"),
            hz("Tone", 800.0, 16000.0, 5200.0),
            param("Crunch", 0.0, 24.0, 6.0, "dB"),
            param("Mix", 0.0, 100.0, 100.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        let mut retune = Retune::default();
        retune.mark();
        Self {
            rate,
            delay: Delay::new(0.05, rate as u32),
            tone: Biquad::default(),
            wobble: Smoothed::new(rate, 0.35),
            noise: Smoothed::new(rate, 0.2),
            cutoff: Smoothed::new(rate, 5200.0),
            drive: Smoothed::new(rate, 2.0),
            mix: Smoothed::new(rate, 1.0),
            phase: 0.0,
            flutter: 0.0,
            seed: 22222,
            hiss: 0.0,
            presence: 0.0,
            retune,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.wobble.set(value / 100.0),
            1 => self.noise.set(value / 100.0),
            2 => {
                self.cutoff.set(value);
                self.retune.mark();
            }
            3 => self.drive.set(db_to_gain(value) as f64),
            4 => self.mix.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.delay.clear();
        self.tone.clear();
        self.presence = 0.0;
        for s in [
            &mut self.wobble,
            &mut self.noise,
            &mut self.cutoff,
            &mut self.drive,
            &mut self.mix,
        ] {
            s.snap();
        }
        self.retune.mark();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        for frame in audio {
            let moved = self.cutoff.advance();
            if self.retune.due(moved) {
                self.tone.lowpass(self.rate, self.cutoff.value(), 0.6);
            }
            let wobble = self.wobble.next();
            let noise = self.noise.next() as f32;
            let drive = self.drive.next() as f32;
            let mix = self.mix.next() as f32;
            self.phase = (self.phase + 0.6 / self.rate).fract();
            self.flutter = (self.flutter + 7.3 / self.rate).fract();
            let ms =
                12.0 + wobble * (6.0 * (TAU * self.phase).sin() + 0.8 * (TAU * self.flutter).sin());
            self.delay.write(*frame);
            let tape = self.delay.read(ms.max(0.5) / 1000.0 * self.rate);
            self.seed = self.seed.wrapping_mul(1664525).wrapping_add(1013904223);
            let white = self.seed as f32 / 2147483648.0 - 1.0;
            self.hiss += 0.25 * (white - self.hiss);
            let level = tape[0].abs().max(tape[1].abs()).min(1.0);
            self.presence +=
                if level > self.presence { 0.01 } else { 0.00005 } * (level - self.presence);
            let hiss = self.hiss * noise * 0.04 * self.presence.sqrt();
            for c in 0..2 {
                let worn = ((tape[c] * drive).tanh() / drive.max(1.0).sqrt()) + hiss;
                let wet = self.tone.process(c, worn);
                frame[c] += (wet - frame[c]) * mix;
            }
        }
    }
}

/// Two crossfading taps reading a delay line faster or slower than it is written.
pub struct PitchShift {
    rate: f64,
    delay: Delay,
    semitones: f64,
    cents: f64,
    mix: Smoothed,
    phase: f64,
}
impl PitchShift {
    const WINDOW: f64 = 0.06;
}
impl Plugin for PitchShift {
    const INFO: Info = Info::effect(
        "org.ondera.stock.pitchshift",
        "Pitch Shift",
        VENDOR,
        "Pitch",
    )
    .describe(
        "Shifts pitch up or down an octave without changing length: harmonies, octaves, detune.",
    );
    fn params() -> Vec<ParamSpec> {
        vec![
            ParamSpec {
                steps: 24,
                ..param("Semitones", -12.0, 12.0, 7.0, "st")
            },
            param("Fine", -100.0, 100.0, 0.0, "ct"),
            param("Mix", 0.0, 100.0, 50.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            delay: Delay::new(Self::WINDOW * 2.0 + 0.01, rate as u32),
            semitones: 7.0,
            cents: 0.0,
            mix: Smoothed::new(rate, 0.5),
            phase: 0.0,
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            // Semitones are steps, and the ratio moves the read head's speed, not its place:
            // neither clicks.
            0 => self.semitones = value.round(),
            1 => self.cents = value,
            2 => self.mix.set(value / 100.0),
            _ => {}
        }
    }
    fn reset(&mut self) {
        self.delay.clear();
        self.mix.snap();
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], _: &ProcessContext) {
        let ratio = 2f64.powf((self.semitones + self.cents / 100.0) / 12.0);
        let window = Self::WINDOW * self.rate;
        // The read head drifts (1 - ratio) samples per sample; one ramp spans the window.
        let step = (1.0 - ratio) / window;
        for frame in audio {
            let mix = self.mix.next() as f32;
            self.delay.write(*frame);
            self.phase = (self.phase + step).rem_euclid(1.0);
            let mut wet = [0f32; 2];
            for tap in 0..2 {
                let p = (self.phase + tap as f64 * 0.5).fract();
                let gain = (std::f64::consts::PI * p).sin() as f32;
                let v = self.delay.read(1.0 + p * window);
                wet[0] += v[0] * gain * gain;
                wet[1] += v[1] * gain * gain;
            }
            frame[0] += (wet[0] - frame[0]) * mix;
            frame[1] += (wet[1] - frame[1]) * mix;
        }
    }
}

/// Sidechain-style ducking locked to the song's beat: no kick routing needed.
pub struct Pump {
    rate: f64,
    division: u8,
    depth: f32,
    curve: f64,
    offset: f64,
    free: f64,
    gain: Smoother,
}
impl Plugin for Pump {
    const INFO: Info = Info::effect("org.ondera.stock.pump", "Pump", VENDOR, "Dynamics")
        .describe("Ducks on every beat and swells back, in time with the song. The sidechain sound without the routing.");
    fn params() -> Vec<ParamSpec> {
        vec![
            choice("Every", &["1/2", "1/4", "1/8", "1/16"], 1),
            param("Depth", 0.0, 100.0, 70.0, "%"),
            param("Recovery", 5.0, 100.0, 45.0, "%"),
            param("Offset", 0.0, 100.0, 0.0, "%"),
        ]
    }
    fn new(rate: f64) -> Self {
        Self {
            rate,
            division: 1,
            depth: 0.7,
            curve: 0.45,
            offset: 0.0,
            free: 0.0,
            gain: Smoother::new(rate, 0.003, 1.0),
        }
    }
    fn set_param(&mut self, index: usize, value: f64) {
        match index {
            0 => self.division = value.round() as u8,
            1 => self.depth = (value / 100.0) as f32,
            2 => self.curve = value / 100.0,
            3 => self.offset = value / 100.0,
            _ => {}
        }
    }
    fn process(&mut self, audio: &mut [[f32; 2]], _: &[NoteEvent], ctx: &ProcessContext) {
        let beats = [2.0, 1.0, 0.5, 0.25][self.division.min(3) as usize];
        let per_sample = ctx.tempo.max(20.0) / 60.0 / self.rate / beats;
        // Follow the song while it plays; keep pumping at tempo when it is stopped.
        let mut cycle = if ctx.playing {
            (ctx.position_beats / beats).rem_euclid(1.0)
        } else {
            self.free
        };
        for frame in audio {
            let p = (cycle - self.offset).rem_euclid(1.0);
            let recovered = (p / self.curve.max(0.05)).min(1.0);
            let shape = (recovered * recovered * (3.0 - 2.0 * recovered)) as f32;
            self.gain.set(1.0 - self.depth * (1.0 - shape));
            let g = self.gain.step();
            frame[0] *= g;
            frame[1] *= g;
            cycle = (cycle + per_sample).fract();
        }
        self.free = cycle;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn the_abi_2_tables_list_the_same_plugins_in_the_same_order() {
        for (index, table) in TABLES_V2.iter().enumerate() {
            let manifest = unsafe { ondera_plugin::ffi::read_manifest(&table.base) }.unwrap();
            assert_eq!(manifest, MANIFESTS[index]);
        }
    }
    #[test]
    fn every_stock_plugin_instantiates_with_matching_parameters() {
        for name in INSTRUMENTS.iter().chain(EFFECTS.iter()) {
            let instance = create(name, 48000).expect(name);
            assert_eq!(instance.editor.params().len(), params(name).len());
            assert!(instance.processor.is_some());
            assert_eq!(instance.editor.descriptor().id, format!("stock:{name}"));
        }
        assert_eq!(MANIFESTS.len(), INSTRUMENTS.len() + EFFECTS.len());
    }
    fn ctx() -> ProcessContext {
        ProcessContext {
            tempo: 120.0,
            ..ProcessContext::default()
        }
    }
    /// A gain step that arrives while the plugin runs becomes a monotonic ramp, then lands
    /// exactly on the unsmoothed gain.
    #[test]
    fn a_gain_step_ramps_monotonically_and_settles_bit_exact() {
        let rate = 48000.0;
        let mut utility = Utility::new(rate);
        utility.set_param(0, 0.0);
        let mut audio = vec![[1.0f32, 1.0]; 64];
        utility.process(&mut audio, &[], &ctx());
        assert!(
            audio.iter().all(|f| f[0] == 1.0),
            "a fresh value is not glided"
        );
        utility.set_param(0, -12.0);
        let mut audio = vec![[1.0f32, 1.0]; 4800];
        utility.process(&mut audio, &[], &ctx());
        let target = db_to_gain(-12.0);
        assert!(
            audio[0][0] < 1.0 && audio[0][0] > 0.9,
            "no jump: {}",
            audio[0][0]
        );
        for pair in audio.windows(2) {
            assert!(pair[1][0] <= pair[0][0], "monotonic");
        }
        assert!(
            audio[480][0] > target,
            "still moving after one time constant"
        );
        assert_eq!(audio[4799][0], target, "settled on the exact gain");
        // A settled gain gives the same bits as a plugin that never moved.
        let mut fresh = Utility::new(rate);
        fresh.set_param(0, -12.0);
        let input: Vec<[f32; 2]> = (0..512)
            .map(|i| [(i as f32 * 0.01).sin(), (i as f32 * 0.013).cos()])
            .collect();
        let (mut a, mut b) = (input.clone(), input.clone());
        utility.process(&mut a, &[], &ctx());
        fresh.process(&mut b, &[], &ctx());
        assert_eq!(a, b);
        assert!(a.iter().zip(&input).all(|(o, i)| o[0] == i[0] * target));
    }
    /// Values set before the first sample, and after a reset, are taken at once.
    #[test]
    fn values_set_before_processing_or_after_a_reset_do_not_glide() {
        let mut utility = Utility::new(48000.0);
        utility.set_param(0, 0.0);
        utility.set_param(0, -6.0);
        let mut audio = vec![[1.0f32, 1.0]; 4];
        utility.process(&mut audio, &[], &ctx());
        assert_eq!(audio[0][0], db_to_gain(-6.0));
        utility.reset();
        utility.set_param(0, 6.0);
        utility.process(&mut audio, &[], &ctx());
        assert_eq!(audio[0][0], db_to_gain(-6.0) * db_to_gain(6.0));
    }
    /// Every stock effect, through its vtable, stays finite when all of its continuous
    /// parameters jump to their maximum in the middle of a signal.
    #[test]
    fn stock_effects_stay_finite_when_every_parameter_jumps() {
        let rate = 48000u32;
        for name in EFFECTS {
            let instance = create(name, rate).expect(name);
            let mut processor = instance.processor.expect(name);
            let params = instance.editor.params().to_vec();
            let context = ctx();
            let signal = |i: usize| (i as f32 * TAU as f32 * 220.0 / rate as f32).sin() * 0.25;
            let run = |processor: &mut Box<dyn crate::plugin::Processor>,
                       start: usize,
                       changes: &[crate::plugin::ParamChange]| {
                let mut audio: Vec<[f32; 2]> = (start..start + 256)
                    .map(|i| [signal(i), signal(i)])
                    .collect();
                processor.process(&mut audio, &[], changes, &context);
                audio
            };
            let mut out = Vec::new();
            for block in 0..8 {
                out.extend(run(&mut processor, block * 256, &[]));
            }
            // Move every continuous parameter to its maximum at once, mid-signal.
            let changes: Vec<_> = params
                .iter()
                .enumerate()
                .filter(|(_, p)| p.steps == 0)
                .map(|(i, p)| crate::plugin::ParamChange {
                    id: i as u32,
                    value: p.max,
                    frame: 0,
                })
                .collect();
            out.extend(run(&mut processor, 8 * 256, &changes));
            for block in 9..16 {
                out.extend(run(&mut processor, block * 256, &[]));
            }
            assert!(
                out.iter().flatten().all(|s| s.is_finite()),
                "{name} stays finite"
            );
        }
    }
    #[test]
    fn factory_presets_name_real_plugins_and_parameters_in_range() {
        for (plugin, preset, values) in FACTORY_PRESETS {
            let params = params(plugin);
            assert!(!params.is_empty(), "{plugin} for preset {preset}");
            for (id, value) in *values {
                let p = &params[*id as usize];
                assert!(
                    (p.min..=p.max).contains(value),
                    "{plugin} / {preset}: {} = {value} outside {}..{}",
                    p.name,
                    p.min,
                    p.max
                );
            }
        }
    }
}
