/**
 * Ink. Print and e-paper: one ink, one paper, one red pencil. No simulated light at
 * all: surfaces are the paper, structure is 1 px rules, and state is shown the way a
 * printer would, by inverting (a selected segment or an engaged switch is solid ink
 * with paper type). The only colour besides the track colours is vermilion, used for
 * the playhead, the agent and whatever is lit. Corners are square.
 *
 * Light is warm paper with near-black ink; dark is the same page inverted, paper-white
 * type on carbon, for a dim room. Nothing floats except menus and dialogs, and they
 * cast a hard offset shadow like a card laid on the page.
 */
import { eqGrid, NO_CANVAS_SHADOWS } from "./materials";
import {
  alpha,
  families,
  ok,
  type ColorKey,
  type FillKey,
  type GradientKey,
  type LineKey,
  type Mode,
  type ShadowKey,
  type ThemeSpec,
} from "./schema";

/** Swiss grotesque where the system has one; Manrope everywhere else. */
const FONT =
  "'Helvetica Neue', Helvetica, 'Inter', 'Manrope', system-ui, sans-serif";
const RADIUS = {
  xs: 0,
  sm: 1,
  clip: 1,
  button: 1,
  md: 2,
  control: 2,
  lg: 2,
  glass: 2,
  window: 8,
};

/** Paper and ink share one warm hue so the page never looks blue. */
const HUE = 90;
const p = (L: number, C = 0.004) => ok(L, C, HUE);

function colors(mode: Mode): Record<ColorKey, string> {
  if (mode === "dark") {
    // Carbon: the page is L .155; ink is paper white.
    const accent = ok(0.7, 0.18, 34);
    return {
      desk: p(0.12, 0.003),
      wellDeep: p(0.115, 0.003),
      groove: p(0.29),
      grooveAlt: p(0.13, 0.003),
      timelineEmpty: p(0.135, 0.003),
      timeline: p(0.155, 0.003),
      timelineAgent: ok(0.18, 0.025, 34),
      timelineSelected: p(0.19),
      editor: p(0.155, 0.003),
      ruler: p(0.165),
      materialCard: p(0.175),
      agentPanel: p(0.155, 0.003),
      panel: p(0.165),
      logEntry: p(0.18),
      raised: p(0.2),
      controlFace: p(0.36),
      controlTop: p(0.19),
      controlBottom: p(0.19),
      pressedTop: p(0.12, 0.003),
      pressedBottom: p(0.12, 0.003),
      transportTop: p(0.165),
      transportBottom: p(0.165),
      // Inverted: the selected segment is solid paper.
      segmentTop: p(0.92),
      segmentBottom: p(0.92),
      thumbTop: p(0.92),
      thumbBottom: p(0.92),
      knobHi: p(0.19),
      knobLo: p(0.19),
      knobBigHi: p(0.19),
      knobBigLo: p(0.19),
      knobInnerHi: p(0.19),
      knobInnerLo: p(0.19),
      capTop: p(0.92),
      capMid: p(0.92),
      capBottom: p(0.92),
      headerTop: p(0.165),
      headerBottom: p(0.165),
      headerSelectedTop: p(0.215),
      headerSelectedBottom: p(0.215),
      headerAgentTop: ok(0.2, 0.03, 34),
      headerAgentBottom: ok(0.2, 0.03, 34),
      insertTop: p(0.19),
      insertBottom: p(0.19),
      chipTop: p(0.2),
      chipBottom: p(0.2),
      trafficLight: p(0.34),
      inkBright: p(0.97, 0.006),
      ink100: p(0.93, 0.006),
      inkControl: p(0.88, 0.006),
      inkDim: p(0.8),
      ink300: p(0.72),
      ink500: p(0.61),
      inkSeparator: p(0.4),
      inkKeyWhite: p(0.45),
      wellInk: p(0.97, 0.006),
      wellInkDim: p(0.72),
      wellInkFaint: p(0.6),
      keyWhite: p(0.92, 0.006),
      keyBlack: p(0.2),
      // Meters print in paper; only the overload is red.
      led: p(0.9, 0.006),
      ledOff: p(0.24),
      ledGlow: "transparent",
      ledGlowSoft: "transparent",
      ledHot: accent,
      accent,
      accentHi: accent,
      accentLo: accent,
      accentInk: p(0.12, 0.003),
      noteTop: p(0.88, 0.006),
      noteBottom: p(0.88, 0.006),
      eqCurve: accent,
      eqHandle: p(0.97),
      eqFill: accent,
      ...families(0.76, 0.1),
      neutralDot: p(0.45),
      menu: p(0.19),
      menuHover: p(0.26),
      menuSeparator: p(0.3),
      indicator: p(0.95, 0.006),
      danger: ok(0.72, 0.17, 18),
      scrim: "rgba(0,0,0,.55)",
    };
  }
  // Paper: the page is L .965, ink is L .19.
  const accent = ok(0.58, 0.2, 33);
  return {
    desk: p(0.9, 0.008),
    wellDeep: p(0.985, 0.006),
    groove: p(0.87, 0.008),
    grooveAlt: p(0.945, 0.008),
    timelineEmpty: p(0.935, 0.008),
    timeline: p(0.975, 0.008),
    timelineAgent: ok(0.955, 0.02, 40),
    timelineSelected: p(0.945, 0.01),
    editor: p(0.975, 0.008),
    ruler: p(0.955, 0.008),
    materialCard: p(0.99, 0.004),
    agentPanel: p(0.97, 0.008),
    panel: p(0.955, 0.008),
    logEntry: p(0.985, 0.006),
    raised: p(0.985, 0.006),
    controlFace: p(0.85, 0.008),
    controlTop: p(0.99, 0.004),
    controlBottom: p(0.99, 0.004),
    pressedTop: p(0.9, 0.008),
    pressedBottom: p(0.9, 0.008),
    transportTop: p(0.955, 0.008),
    transportBottom: p(0.955, 0.008),
    // Inverted: the selected segment is solid ink.
    segmentTop: p(0.2, 0.006),
    segmentBottom: p(0.2, 0.006),
    thumbTop: p(0.2, 0.006),
    thumbBottom: p(0.2, 0.006),
    knobHi: p(0.99, 0.004),
    knobLo: p(0.99, 0.004),
    knobBigHi: p(0.99, 0.004),
    knobBigLo: p(0.99, 0.004),
    knobInnerHi: p(0.99, 0.004),
    knobInnerLo: p(0.99, 0.004),
    capTop: p(0.2, 0.006),
    capMid: p(0.2, 0.006),
    capBottom: p(0.2, 0.006),
    headerTop: p(0.955, 0.008),
    headerBottom: p(0.955, 0.008),
    headerSelectedTop: p(0.915, 0.01),
    headerSelectedBottom: p(0.915, 0.01),
    headerAgentTop: ok(0.94, 0.03, 38),
    headerAgentBottom: ok(0.94, 0.03, 38),
    insertTop: p(0.99, 0.004),
    insertBottom: p(0.99, 0.004),
    chipTop: p(0.935, 0.008),
    chipBottom: p(0.935, 0.008),
    trafficLight: p(0.8, 0.008),
    inkBright: p(0.14, 0.006),
    ink100: p(0.19, 0.006),
    inkControl: p(0.25, 0.006),
    inkDim: p(0.33, 0.006),
    ink300: p(0.42, 0.006),
    ink500: p(0.52, 0.006),
    inkSeparator: p(0.78, 0.006),
    inkKeyWhite: p(0.55),
    wellInk: p(0.14, 0.006),
    wellInkDim: p(0.42, 0.006),
    wellInkFaint: p(0.52, 0.006),
    keyWhite: p(0.995, 0.003),
    keyBlack: p(0.2, 0.006),
    led: p(0.24, 0.006),
    ledOff: p(0.87, 0.008),
    ledGlow: "transparent",
    ledGlowSoft: "transparent",
    ledHot: accent,
    accent,
    accentHi: accent,
    accentLo: accent,
    accentInk: "#ffffff",
    noteTop: p(0.24, 0.006),
    noteBottom: p(0.24, 0.006),
    eqCurve: accent,
    eqHandle: p(0.19, 0.006),
    eqFill: accent,
    ...families(0.5, 0.13),
    neutralDot: p(0.7),
    menu: p(0.99, 0.004),
    menuHover: p(0.925, 0.01),
    menuSeparator: p(0.85, 0.008),
    indicator: p(0.19, 0.006),
    danger: ok(0.52, 0.2, 20),
    scrim: "rgba(40,36,28,.2)",
  };
}

export function ink(mode: Mode): ThemeSpec {
  const dark = mode === "dark";
  const c = colors(mode);
  // `ink(a)` is the foreground at an alpha: rules, tints, ghosts.
  const tint = dark
    ? (a: number) => `rgba(240,236,226,${a})`
    : (a: number) => `rgba(28,26,20,${a})`;
  const solid = c.ink100;
  const paper = dark ? c.timeline : c.materialCard;
  const border = tint(dark ? 0.16 : 0.2);
  const borderStrong = tint(dark ? 0.34 : 0.55);
  const hairline = tint(dark ? 0.07 : 0.08);
  const ac = (a: number) => alpha(c.accent, a);
  const flat = (x: string) => `linear-gradient(${x}, ${x})`;
  /** A card laid on the page: hard offset, no blur. */
  const card = (d: number) =>
    `0 0 0 1px ${borderStrong}, ${d}px ${d}px 0 ${tint(dark ? 0.1 : 0.14)}`;

  const fill: Record<FillKey, string> = {
    glass: dark ? "rgba(30,29,26,.94)" : "rgba(252,250,245,.95)",
    glassAgent: dark ? "rgba(34,30,28,.95)" : "rgba(252,248,244,.96)",
    glassCard: dark ? "rgba(36,33,30,.96)" : "rgba(253,251,247,.97)",
    logLive: ac(dark ? 0.1 : 0.07),
    logChipLive: ac(dark ? 0.18 : 0.12),
    browserHighlight: tint(dark ? 0.08 : 0.07),
    cycleRuler: tint(dark ? 0.16 : 0.13),
    cycleLane: tint(dark ? 0.03 : 0.03),
    clipTitle: dark ? "rgba(0,0,0,.18)" : tint(0.06),
    rowShade: tint(dark ? 0.025 : 0.022),
    blackKeyRow: dark ? "rgba(0,0,0,.2)" : tint(0.045),
    eqGridLine: tint(0.06),
    eqZeroLine: tint(0.16),
    velocity: tint(dark ? 0.3 : 0.4),
    dragGhost: tint(0.1),
    pencilPreview: ac(0.25),
    cycleHandle: solid,
    dropTarget: ac(0.1),
    stepCell: tint(dark ? 0.06 : 0.05),
    hover: tint(dark ? 0.06 : 0.05),
    fadeShade: dark ? "rgba(0,0,0,.4)" : tint(0.16),
    fadeHandle: solid,
    markerFlag: alpha(paper, 0.94),
  };

  const line: Record<LineKey, string> = {
    barLine: tint(dark ? 0.1 : 0.13),
    beatLine: tint(dark ? 0.035 : 0.05),
    rulerBar: tint(dark ? 0.45 : 0.6),
    rulerTick: tint(dark ? 0.16 : 0.22),
    cycleEdge: solid,
    editorBar: tint(dark ? 0.11 : 0.14),
    editorBeat: tint(dark ? 0.04 : 0.055),
    waveform: tint(dark ? 0.82 : 0.8),
    waveformMid: tint(dark ? 0.3 : 0.3),
    midiNote: tint(dark ? 0.85 : 0.82),
    clipName: tint(dark ? 0.95 : 0.92),
    clipTitleBottom: tint(dark ? 0.12 : 0.16),
    clipHighlight: "transparent",
    clipContact: tint(dark ? 0.25 : 0.35),
    clipSelected: solid,
    cellDivider: hairline,
    dividerDark: border,
    laneTop: "transparent",
    laneBottom: tint(dark ? 0.09 : 0.1),
    rulerBottom: borderStrong,
    faderLine: tint(dark ? 0.5 : 0.6),
    faderLineHi: "transparent",
    milled: "transparent",
    milledHi: "transparent",
    dragGhostEdge: tint(0.6),
    noteSelected: c.accent,
    noteHighlight: "transparent",
    splitGuide: ac(0.95),
    staff: tint(0.4),
    noteHead: c.ink100,
    border,
    borderStrong,
    hairline,
    fadeCurve: tint(0.85),
    marker: c.accent,
    markerLane: ac(0.3),
  };

  const ring = `inset 0 0 0 1px ${border}`;
  const ringStrong = `inset 0 0 0 1px ${borderStrong}`;
  const none = "none";
  const rule = `inset 0 -1px 0 ${border}`;

  const shadow: Record<ShadowKey, string> = {
    raised: ring,
    raisedSm: ring,
    pressed: ringStrong,
    lit: none,
    knob: ringStrong,
    knobBig: ringStrong,
    knobInner: none,
    knobIndicator: none,
    faderCap: `0 0 0 1px ${solid}`,
    thumb: `0 0 0 1px ${solid}`,
    groove: none,
    grooveSoft: none,
    grooveShallow: ring,
    grooveSend: none,
    wellDeep: ringStrong,
    wellInput: ring,
    wellValue: none,
    segment: none,
    clip: none,
    clipAgent: `0 0 0 1.5px ${c.accent}`,
    clipSelected: `0 0 0 2px ${solid}`,
    ledLit: none,
    ledAccent: none,
    ledOff: none,
    ledEmpty: ring,
    glass: card(3),
    glassAgent: `0 0 0 1px ${c.accent}, 3px 3px 0 ${ac(0.25)}`,
    glassCard: `0 0 0 1px ${c.accent}, 4px 4px 0 ${ac(0.2)}`,
    accentDot: none,
    accentDotLg: none,
    accentBar: none,
    playhead: none,
    playheadRuler: none,
    headerCell: `inset -1px 0 0 ${border}, inset 0 -1px 0 ${hairline}`,
    headerCellAgent: `inset 3px 0 0 ${c.accent}, inset -1px 0 0 ${border}, inset 0 -1px 0 ${hairline}`,
    headerColumn: `inset -1px 0 0 ${border}`,
    colorStrip: none,
    swatch: `inset 0 0 0 1px ${border}`,
    swatchSm: none,
    trafficLight: `inset 0 0 0 1px ${border}`,
    // A printer's rule under the menu bar, and a double rule under the transport.
    titleBar: `inset 0 -1px 0 ${borderStrong}`,
    transport: `inset 0 -1px 0 ${borderStrong}, inset 0 -3px 0 ${c.transportTop}, inset 0 -4px 0 ${border}`,
    toolbar: rule,
    toolbarEditor: rule,
    rulerCorner: `inset -1px 0 0 ${border}, inset 0 -1px 0 ${borderStrong}`,
    panelLeft: `inset -1px 0 0 ${borderStrong}`,
    panelRight: `inset 1px 0 0 ${borderStrong}`,
    panelAgent: `inset 1px 0 0 ${borderStrong}`,
    panelAgentRail: `inset 1px 0 0 ${borderStrong}`,
    editorPane: `inset 0 1px 0 ${borderStrong}`,
    keyColumn: `inset -1px 0 0 ${borderStrong}`,
    keyRow: `inset 0 -1px 0 ${hairline}`,
    divider: rule,
    dividerTop: none,
    logEntry: ring,
    logChip: ring,
    insert: ring,
    insertEmpty: `inset 0 0 0 1px ${hairline}`,
    ledInsertOff: ring,
    window: `0 0 0 1px ${borderStrong}, 8px 8px 0 ${tint(0.12)}`,
    sendKey: none,
    menu: card(4),
    dialog: card(6),
    inlineInput: `0 0 0 1.5px ${solid}`,
    note: none,
    faderLineHi: none,
    milledHi: none,
    plate: ring,
    focus: `0 0 0 2px ${c.accent}`,
  };

  const gradient: Record<GradientKey, string> = {
    raised: flat(c.controlTop),
    raisedHover: flat(dark ? p(0.25) : p(0.94, 0.01)),
    pressed: flat(c.pressedTop),
    lit: flat(c.accent),
    transport: flat(c.transportTop),
    titleBar: flat(c.panel),
    segment: flat(c.segmentTop),
    thumb: flat(c.thumbTop),
    knob: flat(c.knobHi),
    knobBig: flat(c.knobBigHi),
    knobInner: "none",
    faderCap: flat(c.capTop),
    header: flat(c.headerTop),
    headerSelected: flat(c.headerSelectedTop),
    headerAgent: flat(c.headerAgentTop),
    panelHeader: flat(c.panel),
    insert: flat(c.insertTop),
    chip: flat(c.chipTop),
    sendKey: flat(c.accent),
    note: flat(c.noteTop),
    eqGrid: eqGrid(fill.eqGridLine, fill.eqZeroLine),
    dialog: flat(paper),
    dialogHeader: flat(paper),
    plate: flat(c.materialCard),
  };

  return {
    scheme: mode,
    color: c,
    gradient,
    shadow,
    fill,
    line,
    blur: { glass: "0px", glassAgent: "0px", glassCard: "0px" },
    radius: RADIUS,
    // E-paper redraws, it does not glide: very short, no overshoot anywhere.
    motion: {
      fast: "40ms",
      base: "90ms",
      slow: "140ms",
      ease: "cubic-bezier(0.4, 0, 0.2, 1)",
      enter: "cubic-bezier(0.2, 0, 0, 1)",
      exit: "cubic-bezier(0.4, 0, 1, 1)",
      settle: "cubic-bezier(0.2, 0, 0, 1)",
    },
    canvasShadow: NO_CANVAS_SHADOWS,
    // Track colour is a wash on the paper, not a fill.
    clipMix: dark
      ? { faceTop: 44, faceBottom: 44 }
      : { faceTop: 34, faceBottom: 34 },
    fontUi: FONT,
    capsTracking: "0.08em",
    vars: {
      "--display-glow": "0",
      "--ring-glow": "transparent",
      /** Type on an inverted (solid ink) surface. */
      "--ink-reverse": dark ? c.desk : c.materialCard,
      "--ink-solid": solid,
      "--ink-rule": borderStrong,
    },
  };
}
